### ISSUE TITLE
Getting expired id token and access token for active refresh token

### ISSUE THREAD

**Issue by ranshine** [aws-amplify/amplify-android#2224] opened 2023-01-11 14:41 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

   implementation 'com.amplifyframework:aws-auth-cognito:1.35.4'

### Environment information

Gradle 6.7.1
------------------------------------------------------------

Build time:   2020-11-16 17:09:24 UTC
Revision:     2972ff02f3210d2ceed2f1ea880f026acfbab5c0

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          11.0.15 (Azul Systems, Inc. 11.0.15+10-LTS)
OS:           Mac OS X 11.6.5 x86_64

### Describe the bug

I am using aws-amplify cognito library for oauth authentication, i am trying to fetch access token and id token for every 15 mins, sometimes i am getting expired access token and id token.

### Code Snippet

` Amplify.Auth.fetchAuthSession({ it ->
            val session = it as AWSCognitoAuthSession
            when (session.identityId.type) {
                AuthSessionResult.Type.SUCCESS -> {
                 // storing tokens
                   session.userPoolTokens.value?.idToken  // expired id token
                }
                AuthSessionResult.Type.FAILURE -> {
                    if (session.identityId.error != null) {
                       // logout
                    }
                }
            }`

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by gpanshu** [comment] 2023-01-27 17:03
This is a duplicate of https://github.com/aws-amplify/amplify-android/issues/1763. Please see the workaround for force refresh if you are finding that sometimes the tokens returned are expired. Alternatively if upgrading is an option for you I would recommend upgrading to our V2 version where we have rewritten the entire library in Kotlin.

**Closed by gpanshu** 2023-01-27 17:03 UTC
Labels: bug, duplicate, auth
