### ISSUE TITLE
Hosted UI pre-signUp lambda trigger callback error message in android front-end 

### ISSUE THREAD

**Issue by AsitDixit** [aws-amplify/amplify-android#1907] opened 2022-08-24 06:11 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line
    implementation 'com.amplifyframework:core:1.36.1'
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'
    implementation "androidx.multidex:multidex:2.0.1"
    implementation 'com.amplifyframework:aws-auth-cognito:1.36.1'

```

</details>

### Environment information

<details>

```
# Put output below this line
gradle version: 7.3.3

```

</details>

### Describe the bug

In hosted UI pre-signup lambda trigger when callback throws an error it should be shown in andorid front-end like I described below: 
**This is my lambda function :**
```
exports.handler = async (event, context, callback) => {
  
     if (event.triggerSource == "PreSignUp_AdminCreateUser") {

   callback(null.event);
     
     } else {return callback(new Error("This provider is not supported"), event);}

};
```
**My Issue :**
Here If someone tries signInWithGoogle with hosted UI, lambda function will return the callback error as ```This provider is not supported``` as we can see there is no ```event.triggerSource=="PreSignUp_ExternalProvider"```. 

But I want ```This provider is not supported``` as a cause of error instead of  ```invalid_request``` in ```AuthException{message=Sign-in with web UI failed, cause=com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthServiceException: invalid_request, recoverySuggestion=See attached exception for more details}``` in android front-end.

 As we can se here there is no ```event.triggerSource == "PreSignUp_SignUp"``` 
 so, When I'm tring signup with email & password it throwing an error to front-end: ```AuthException{message=Sign up failed, cause=com.amazonaws.services.cognitoidentityprovider.model.UserLambdaValidationException: PreSignUp failed with error This provider is not supported. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: UserLambdaValidationException; Request ID: xxxxxxx-xxxxx-xxxxxx-xxxxxxxxx), recoverySuggestion=See attached exception for more details.}```. As we can see this error contains ```PreSignUp failed with error This provider is not supported```.

My problem is with hosted UI instead lambda callback error message, it is showing ```AuthException{message=Sign-in with web UI failed, cause=com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthServiceException: invalid_request, recoverySuggestion=See attached exception for more details}```. I can see cloudwatch log there is error that is ```"This provider is not supported"``` but it is throwing error to front-end as ```invalid-request``` instead of ```"This provider is not supported"```.

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line
Cloudwatch log: 

2022-08-24T05:17:01.810Z	xxxxxxx-xxxxxx-xxxxxx-xxxxxx	ERROR	Invoke Error 	
{
    "errorType": "Error",
    "errorMessage": "This provider is not supported",
    "stack": [
        "Error: This provider is not supported",
        "    at Runtime.exports.handler (/var/task/index.js:8:30)",
        "    at Runtime.handleOnce (file:///var/runtime/index.mjs:548:29)"
    ]
}
```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by eeatonaws** [comment] 2022-09-08 17:52
Closing this issue as it is a duplicate of #1649. Please follow issue #1649 for any updates.

**Closed by eeatonaws** 2022-09-08 17:52 UTC
Labels: duplicate, improvement, auth
