### ISSUE TITLE
Error when trying to update a value

### ISSUE THREAD

**Issue by asmamerc** [aws-amplify/amplify-android#1055] opened 2020-12-15 04:20 UTC
When trying to update some values, the datastore throws exception. The sync engine stops working and even restarting the app wouldn't restart the sync engine, The only way to get rid of this error is to uninstall the app and reinstall it. 

* This does happen with one particular model. Prior to this other models are able to update but following this everything stops. 

** datastore & api version is 1.6.4
```
DataStoreException{message=Wanted 1 metadata for item with id = fea8cb79-a784-48b9-af27-d2d76e215492, but had 0., cause=null, recoverySuggestion=This is likely a bug. please report to AWS.}
        at com.amplifyframework.datastore.syncengine.VersionRepository.extractVersion(VersionRepository.java:89)
        at com.amplifyframework.datastore.syncengine.VersionRepository.lambda$null$0$VersionRepository(VersionRepository.java:63)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$VersionRepository$Kmuu7iZPxyGP2VIH1c1HFJFJDKw.accept(Unknown Source:8)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$query$4$SQLiteStorageAdapter(SQLiteStorageAdapter.java:382)
W/amplify:aws-datastore:     at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$CxFeClFgMnCdkUir6dsRxPfXmiA.run(Unknown Source:10)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
W/amplify:aws-datastore: Error ended observation of mutation outbox: 
    java.lang.RuntimeException: DataStoreException{message=Wanted 1 metadata for item with id = fea8cb79-a784-48b9-af27-d2d76e215492, but had 0., cause=null, recoverySuggestion=This is likely a bug. please report to AWS.}
        at io.reactivex.rxjava3.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
        at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingAwait(BlockingMultiObserver.java:145)
        at io.reactivex.rxjava3.core.Completable.blockingAwait(Completable.java:1490)
        at com.amplifyframework.datastore.syncengine.MutationProcessor.drainMutationOutbox(MutationProcessor.java:118)
        at com.amplifyframework.datastore.syncengine.MutationProcessor.lambda$startDrainingMutationOutbox$1$MutationProcessor(MutationProcessor.java:102)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$MutationProcessor$E9H2I0qolxIT6NJns5-WPOBrLCY.apply(Unknown Source:4)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableFlatMapCompletableCompletable$FlatMapCompletableMainObserver.onNext(ObservableFlatMapCompletableCompletable.java:97)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: DataStoreException{message=Wanted 1 metadata for item with id = fea8cb79-a784-48b9-af27-d2d76e215492, but had 0., cause=null, recoverySuggestion=This is likely a bug. please report to AWS.}
        at com.amplifyframework.datastore.syncengine.VersionRepository.extractVersion(VersionRepository.java:89)
        at com.amplifyframework.datastore.syncengine.VersionRepository.lambda$null$0$VersionRepository(VersionRepository.java:63)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$VersionRepository$Kmuu7iZPxyGP2VIH1c1HFJFJDKw.accept(Unknown Source:8)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$query$4$SQLiteStorageAdapter(SQLiteStorageAdapter.java:382)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$CxFeClFgMnCdkUir6dsRxPfXmiA.run(Unknown Source:10)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

**Comment by richardmcclellan** [comment] 2020-12-15 16:38
Hi @asmamerc, this is a known bug and we are working on a fix.  

Closing as a duplicate of https://github.com/aws-amplify/amplify-android/issues/812

**Closed by richardmcclellan** 2020-12-15 16:38 UTC
Labels: Bug, DataStore

**Comment by asmamerc** [comment] 2020-12-15 19:20
I have looked at that issue multiple times. It doesn't look like this one at all. My initial sync is successful. Everything goes fine until I try to update values on one particular model. After that the error messages are: 
1. DataStoreException{message=Wanted 1 metadata for item with id = xxx, but had 0.
2. Error ended observation of mutation outbox

**Comment by kjones** [comment] 2020-12-15 19:49
There is a small possibility that #1050 could fix this when released. I was getting these same errors until datastore stopped discarding mutation responses from the server.
