### ISSUE TITLE
AmplifyException - Error during subscription

### ISSUE THREAD

**Issue by yogimishra** [aws-amplify/amplify-android#956] opened 2020-11-07 15:26 UTC
I have implemented AppSync via Amplify CLI. Right now I'm just running queries. I haven't implemented any subscription(s) yet. However, I still see subscription errors every time a sync happens. I am not sure why I get this.

```console
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | AmplifyException {message=Error during subscription., cause=AmplifyException {message=Subscription failed., cause=javax.net.ssl.SSLException: Read error: ssl=0xa29b6a00: I/O error during system call, Software caused connection abort, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Evaluate details.}
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.internal.operators.observable.ObservableFlatMap$InnerObserver.onError(ObservableFlatMap.java:577)
	at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
	at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:281)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: AmplifyException {message=Error during subscription., cause=AmplifyException {message=Subscription failed., cause=javax.net.ssl.SSLException: Read error: ssl=0xa29b6a00: I/O error during system call, Software caused connection abort, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Evaluate details.}
	at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$3(AppSyncClient.java:292)
	at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$8gXTT9bgLZGP51blif6hkh7EwIc.accept(lambda)
	at com.amplifyframework.api.aws.SubscriptionOperation.lambda$null$1$SubscriptionOperation(SubscriptionOperation.java:94)
	at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$EfR-sAOj2xzA_-vAoxWBdb2iFk8.accept(lambda)
	at com.amplifyframework.api.aws.SubscriptionEndpoint$Subscription.dispatchError(SubscriptionEndpoint.java:377)
	at com.amplifyframework.api.aws.SubscriptionEndpoint.notifyError(SubscriptionEndpoint.java:204)
	at com.amplifyframework.api.aws.SubscriptionEndpoint.access$000(SubscriptionEndpoint.java:60)
	at com.amplifyframework.api.aws.SubscriptionEndpoint$AmplifyWebSocketListener.onFailure(SubscriptionEndpoint.java:473)
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.kt:592)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:197)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	... 3 more
Caused by: AmplifyException {message=Subscription failed., cause=javax.net.ssl.SSLException: Read error: ssl=0xa29b6a00: I/O error during system call, Software caused connection abort, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
	... 9 more
Caused by: javax.net.ssl.SSLException: Read error: ssl=0xa29b6a00: I/O error during system call, Software caused connection abort
	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:758)
	at okio.InputStreamSource.read(JvmOkio.kt:90)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
	at okio.RealBufferedSource.request(RealBufferedSource.kt:207)
	at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
	... 4 more
```

**Comment by raphkim** [comment] 2020-11-09 19:17
If you are using Amplify DataStore with sync enabled (backed by Amplify API), then the framework will internally set up a subscription to sync your models between local storage and cloud storage. It appears that there is a misconfiguration with your DataStore client (the `SSLException` suggests it may be auth related), so we will need a bit more information. Would you be able to share your code snippet with us so that we may better assist you?

Meanwhile, please verify that [Amplify Auth](https://docs.amplify.aws/lib/auth/getting-started/q/platform/android) and [Amplify API](https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/android) are set up correctly according to the documentation.

**Comment by jamesonwilliams** [comment] 2020-11-09 19:36
Hi @yogimishra! From your stack trace, you appear to be using the [Amplify DataStore](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js#datastore-with-amplify).

The DataStore silently establishes subscriptions to AppSync, when it starts up. It does this around the time of its initial synchronization calls to AppSync. That's why you're seeing subscription stuff in the stack trace. This much is working as designed.

This error looks like our open issue https://github.com/aws-amplify/amplify-android/issues/731:

>  javax.net.ssl.SSLException: Read error: ssl=0xa29b6a00: I/O error during system call, Software caused connection abort

I'll close this issue, so that we can track that issue in 731.

**Closed by jamesonwilliams** 2020-11-09 19:36 UTC
Labels: Clarification Needed, DataStore, Usage Question
