### ISSUE TITLE
Issue with parsing AWSTime in DataStore

### ISSUE THREAD

**Issue by a-melnyk** [aws-amplify/amplify-android#621] opened 2020-07-02 14:31 UTC
Hi all,

I'm having a problem persisting an item to DataStore with a field of **AWSTime** scalar type, I'm getting an exception with "Mutation failed" message, the problem seems to be similar to #590. Please see the schema, code, and the exception below:

schema.graphql:
```graphql
enum Priority {
  LOW
  NORMAL
  HIGH
}

type Todo @model {
  id: ID!
  name: String!
  priority: Priority
  description: String
  duration: AWSTime
}
```

code:
```kotlin
        val item = Todo.builder()
                .name("Test if AWSTime works")
                .priority(Priority.HIGH)
                .description("It should work")
                .duration(Temporal.Time(Calendar.getInstance().time))
                .build()

        Amplify.DataStore.save(
                item,
                { success -> Log.i("Tutorial", "Saved item: " + success.item().name) },
                { error -> Log.e("Tutorial", "Could not save item to DataStore", error) }
        )
```

exception:
```
W/amplify:aws-datastore: Failed to publish a local change = PendingMutation{mutatedItem=Todo {id=d238e5ac-e3ff-4ffb-98d0-1bc298e68745, name=Test if AWSTime works, priority=HIGH, description=It should work, duration=Temporal.Time{localTime='14:08:03.957', zoneOffset='null'}}, classOfMutatedItem=class com.amplifyframework.datastore.generated.model.Todo, mutationType=CREATE, mutationId=7268cf7c-bc6d-11ea-80c6-875908ce5968, predicate=null}
    AmplifyException {message=Mutation failed. Failed mutation = PendingMutation{mutatedItem=Todo {id=d238e5ac-e3ff-4ffb-98d0-1bc298e68745, name=Test if AWSTime works, priority=HIGH, description=It should work, duration=Temporal.Time{localTime='14:08:03.957', zoneOffset='null'}}, classOfMutatedItem=class com.amplifyframework.datastore.generated.model.Todo, mutationType=CREATE, mutationId=7268cf7c-bc6d-11ea-80c6-875908ce5968, predicate=null}. AppSync response contained errors = [GraphQLResponse.Error{message='Variable 'duration' has an invalid value. Unable to parse `{localTime={hour=14, minute=8, nano=957000000, second=3}}` as a valid time.', locations='[GraphQLLocation{line='1', column='21'}]', path='null', extensions='null'}], cause=null, recoverySuggestion=Verify that your AppSync endpoint is able to store Todo models.}
        at com.amplifyframework.datastore.syncengine.MutationProcessor.lambda$null$11(MutationProcessor.java:7)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$MutationProcessor$w1EW1gU2W9mWN5QztizneJ-zhAE.accept(lambda)
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$mutation$4$AppSyncClient(AppSyncClient.java:2)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$nKAFu77xjCuzuWw9lR7faFIdN9U.accept(lambda)
        at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:16)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
W/amplify:aws-datastore: Error ended observation of mutation outbox: 
    java.lang.RuntimeException: AmplifyException {message=Mutation failed. Failed mutation = PendingMutation{mutatedItem=Todo {id=d238e5ac-e3ff-4ffb-98d0-1bc298e68745, name=Test if AWSTime works, priority=HIGH, description=It should work, duration=Temporal.Time{localTime='14:08:03.957', zoneOffset='null'}}, classOfMutatedItem=class com.amplifyframework.datastore.generated.model.Todo, mutationType=CREATE, mutationId=7268cf7c-bc6d-11ea-80c6-875908ce5968, predicate=null}. AppSync response contained errors = [GraphQLResponse.Error{message='Variable 'duration' has an invalid value. Unable to parse `{localTime={hour=14, minute=8, nano=957000000, second=3}}` as a valid time.', locations='[GraphQLLocation{line='1', column='21'}]', path='null', extensions='null'}], cause=null, recoverySuggestion=Verify that your AppSync endpoint is able to store Todo models.}
        at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
        at io.reactivex.internal.observers.BlockingMultiObserver.blockingAwait(BlockingMultiObserver.java:185)
        at io.reactivex.Completable.blockingAwait(Completable.java:1256)
        at com.amplifyframework.datastore.syncengine.MutationProcessor.lambda$startDrainingMutationOutbox$1$MutationProcessor(MutationProcessor.java:6)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$MutationProcessor$iu5hAaGgWV8-jjRjPW1wTtFQOwM.apply(lambda)
        at io.reactivex.internal.operators.observable.ObservableFlatMapCompletableCompletable$FlatMapCompletableMainObserver.onNext(ObservableFlatMapCompletableCompletable.java:97)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: AmplifyException {message=Mutation failed. Failed mutation = PendingMutation{mutatedItem=Todo {id=d238e5ac-e3ff-4ffb-98d0-1bc298e68745, name=Test if AWSTime works, priority=HIGH, description=It should work, duration=Temporal.Time{localTime='14:08:03.957', zoneOffset='null'}}, classOfMutatedItem=class com.amplifyframework.datastore.generated.model.Todo, mutationType=CREATE, mutationId=7268cf7c-bc6d-11ea-80c6-875908ce5968, predicate=null}. AppSync response contained errors = [GraphQLResponse.Error{message='Variable 'duration' has an invalid value. Unable to parse `{localTime={hour=14, minute=8, nano=957000000, second=3}}` as a valid time.', locations='[GraphQLLocation{line='1', column='21'}]', path='null', extensions='null'}], cause=null, recoverySuggestion=Verify that your AppSync endpoint is able to store Todo models.}
        at com.amplifyframework.datastore.syncengine.MutationProcessor.lambda$null$11(MutationProcessor.java:7)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$MutationProcessor$w1EW1gU2W9mWN5QztizneJ-zhAE.accept(lambda)
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$mutation$4$AppSyncClient(AppSyncClient.java:2)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$nKAFu77xjCuzuWw9lR7faFIdN9U.accept(lambda)
        at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:16)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
```

**Comment by richardmcclellan** [comment] 2020-07-05 21:59
Hi @a-melnyk,  the `Temporal` types currently work with the `API` category but don't yet work the `DataStore` category.   As a workaround, if you need a solution now, you could store your date using a `String` type.    That said, we are currently working on adding proper support for the `Temporal` types in `DataStore`, which should be available soon.

Closing this ticket since it is a duplicate of https://github.com/aws-amplify/amplify-android/issues/590.

**Closed by richardmcclellan** 2020-07-05 21:59 UTC

**Comment by richardmcclellan** [comment] 2020-07-16 20:51
@a-melnyk `Temporal` types are now supported with `DataStore`, in version `1.1.0`, which we just released today.   If you still have issues, feel free to comment on this issue with details.
