### ISSUE TITLE
Auth signOut after signInWithSocialWebUI does not clear browser session

### ISSUE THREAD

**Issue by rohitmahajan-ap** [aws-amplify/amplify-android#2858] opened 2024-06-24 18:22 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line

  def amplify_version = "1.37.5"
    def amplify_kotlin_version = "0.21.0"

 implementation "com.amplifyframework:core:$amplify_version"
    implementation "com.amplifyframework:aws-api:$amplify_version"
    implementation "com.amplifyframework:aws-api-appsync:$amplify_version"
    implementation "com.amplifyframework:aws-auth-cognito:$amplify_version"
    implementation "com.amplifyframework:aws-datastore:$amplify_version"
    implementation "com.amplifyframework:aws-storage-s3:$amplify_version"
    implementation "com.amplifyframework:core-kotlin:$amplify_kotlin_version"
    implementation "androidx.browser:browser:1.4.0"
```

</details>

### Environment information

<details>

```
# Put output below this line
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists

```

</details>

### Describe the bug

When a user installs the app, he is able to login using Microsoft by entering email and password. But when the user is logged out and tries again to login, signInWithSocialWebUI doesn't let the user enter email and password, it just automatically logs in with the previous account.

### Code Snippet

```Kotlin
// Put your code below this line.
Amplify.Auth.signInWithSocialWebUI(provider, requireActivity(),
                    {
                            result ->
                        session.isSsoLogin = true
                        session.loggedInEmailId = email
                        authViewModel.fetchTokenAmplify()
                    },
                    {
                            error ->
                        Log.e("AuthQuickstart", "Sign in failed", error)
                    }
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### amplifyconfiguration.json

```
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "ap-qa-api": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://*********4.appsync-api.us-east-1.amazonaws.com/graphql",
                    "region": "us-east-1",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS",
                    "apiKey": "da2-dwmairjnb5c2jibyqy6hfjeivi",
                    "realtimeEndpoint": "wss://*********4.appsync-realtime-api.us-east-1.amazonaws.com/graphql"

                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify/cli",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "AppSync": {
                    "Default": {
                        "ApiUrl": "https://*********4.appsync-api.us-east-1.amazonaws.com/graphql",
                        "Region": "us-east-1",
                        "AuthMode": "AMAZON_COGNITO_USER_POOLS",
                        "ClientDatabasePrefix": "ap-qa-api_AMAZON_COGNITO_USER_POOLS",
                        "realtimeEndpoint": "wss://*********4.appsync-api.us-east-1.amazonaws.com/graphql"
                    },
                    "ap-qa-api_API_KEY": {
                        "ApiUrl": "https://*********4.appsync-api.us-east-1.amazonaws.com/graphql",
                        "Region": "us-east-1",
                        "AuthMode": "API_KEY",
                        "ApiKey": "da2-*************",
                        "ClientDatabasePrefix": "ap-qa-api_API_KEY",
                        "realtimeEndpoint": "wss://*********4.appsync-api.us-east-1.amazonaws.com/graphql"
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-east-1_vP0W8cs8h",
                        "AppClientId": "***********",
                        "Region": "us-east-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "ap-wdfwef-****.auth.us-east-1.amazoncognito.com",
                            "AppClientId": "*****************",
                            "SignInRedirectURI": "assetpanda://sign-in",
                            "SignOutRedirectURI": "assetpanda://sign-out",
                            "Scopes": [
                                "aws.cognito.signin.user.admin",
                                "email",
                                "openid",
                                "phone",
                                "profile"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [],
                        "usernameAttributes": [
                            "EMAIL"
                        ],
                        "signupAttributes": [
                            "EMAIL"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": [
                                "REQUIRES_LOWERCASE",
                                "REQUIRES_UPPERCASE",
                                "REQUIRES_NUMBERS",
                                "REQUIRES_SYMBOLS"
                            ]
                        },
                        "mfaConfiguration": "OPTIONAL",
                        "mfaTypes": [
                            "TOTP"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                }
            }
        }
    }
}
```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by phantumcode** [comment] 2024-06-24 18:35
@rohitmahajan-ap Thanks for submitting the issue.  We will investigate and provide updates here.

**Comment by tylerjroach** [comment] 2024-06-24 19:01
This is true for all social sign ins (Facebook, Google, Microsoft Entra, etc). It is a limitation with HostedUI and how Android CustomTabs function. In your case, the signed in cookie is owned by Microsoft. We can only clear credentials on the Cognito side. 

For SAML providers, there is an additional config to add a SAML Sign Out flow that is meant to allow clearing all SAML credentials. However, Microsoft Entra does not appear to support sending the LogoutResponse in the required format. See https://github.com/aws-amplify/amplify-android/issues/2839 and specifically https://github.com/aws-amplify/amplify-android/issues/2839#issuecomment-2160856849.

The customer on that ticket is stating a difference in behavior between Amplify v1 and v2 that we are still looking into. Since this ticket is a duplicate of https://github.com/aws-amplify/amplify-android/issues/2839, I will close this one. Please follow the linked ticket for future updates with Entra.

**Closed by tylerjroach** 2024-06-24 19:01 UTC
Labels: pending-triage
