### ISSUE TITLE
Sign in with web UI failed

### ISSUE THREAD

**Issue by developerRojina** [aws-amplify/amplify-android#552] opened 2020-06-04 09:11 UTC
Hello I am receiving `AmplifyException`  when I login using Facebook/Google. 

You can see my manifest here:
```xml
<activity
        android:name=".login.SocialLoginActivity"
        android:label="@string/title_activity_social_login"
        android:theme="@style/AppTheme.NoActionBar"
        android:launchMode="singleInstance">
    <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="myapp" />
    </intent-filter>
</activity>

```
And here is my Activity:
```kotlin
class SocialLoginActivity : AppCompatActivity() {

    lateinit var loginType: String
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_social_login)
        //  setUpToolBar("Social")
        if (intent != null && intent.hasExtra(AppText.ARG_PARAM_SOCIAL_LOGIN_TYPE))
            loginType = intent.extras.getString(AppText.ARG_PARAM_SOCIAL_LOGIN_TYPE)

        Timber.d("the login type is:" + loginType)
        if (loginType.equals("facebook")) {
            Amplify.Auth.signInWithSocialWebUI(
                AuthProvider.facebook(),
                this,
                { result ->
                    Timber.d(result.toString())
                    handleLoginSuccess()
                },
                { error ->
                    Timber.d(error.toString())
                    handleLoginFailure(error.toString())
                }
            )
        } else if (loginType.equals("google")) {
            Amplify.Auth.signInWithSocialWebUI(
                AuthProvider.google(),
                this,
                { result -> handleLoginSuccess() },
                { error ->
                    Timber.d(error.toString())
                    handleLoginFailure(error.message.toString()) }
            )
        }
    }

    override fun onNewIntent(intent: Intent?) {
        super.onNewIntent(intent)
        Timber.d("inside on New intent called" + intent.toString())
        if (intent?.scheme != null && "myapp".equals(intent?.scheme)) {
            Timber.d("inside handle webui signin")
            Amplify.Auth.handleWebUISignInResponse(intent)
            // authViewModel.handleSocialSignIn(intent)
        }
    }

    fun handleLoginFailure(failureMessage: String) {
        Timber.d("inside failure")
        //Toast.makeText(this, failureMessage, Toast.LENGTH_SHORT)
        finish()
    }
    fun handleLoginSuccess() {
        Timber.d("inside handle login suxxess")
      //  finish()
        startSplashActivity()
    }
}
```

The error is:
> AmplifyException {message=Sign in with web UI failed, cause=com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthNavigationException: user cancelled, recoverySuggestion=See attached exception for more details}

**Comment by TrekSoft** [comment] 2020-06-08 18:41
Hey, so that's a valid error if the user cancels out of the web view which pops up without signing in. Is this happening even if the user signs in successfully?

**Comment by developerRojina** [comment] 2020-06-09 10:52
Yes @TrekSoft  I am getting AmplifyException but  the user signs in successfully. It is a weird scenario.

**Comment by TrekSoft** [comment] 2020-06-09 15:07
Ok yeah so this appears to be due to this underlying cause in the library we've tentatively built Auth on top of: https://github.com/aws-amplify/aws-sdk-android/issues/871

I'll be looking into a fix for this here.

**Comment by developerRojina** [comment] 2020-06-11 04:48
@TrekSoft  The log is being printed inside the error and the onNewIntent is not called.
The error that got printed is:
 AmplifyException {message=Sign in with web UI failed, cause=com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthNavigationException: user cancelled, recoverySuggestion=See attached exception for more details}

**Comment by TrekSoft** [comment] 2020-06-11 15:12
Ok so if onNewIntent is not being called, there's some problem in your setup. Can you post the SignInRedirectURI and SignOutRedirectURI values you have in the amplifyconfiguration.json?

**Comment by developerRojina** [comment] 2020-06-12 06:46
@TrekSoft  These are the SignInRedirectURI and SignOutRedirectURI
            "SignInRedirectURI": "myapp://callback/",
            "SignOutRedirectURI": "myapp://signout/",

**Comment by TrekSoft** [comment] 2020-06-12 15:08
Hmm, this is very strange. I'll have to test your sample code for myself sometime here to see if I can replicate it.

**Comment by jamesonwilliams** [comment] 2020-07-01 13:44
@TrekSoft Maybe this is something we can have on-call look at?

**Comment by jigneshjain1** [comment] 2020-07-06 08:45
@TrekSoft I am getting the same signin with web UI failed error, while trying to login 1st time after logout.

This my manifest,
        <activity
            android:name=".ui.login.AuthActivity"
            android:launchMode="singleInstance">

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="myapp" />
            </intent-filter>
        </activity>

I am calling below function on button click of fragment resided in AuthActivity.

            activity?.let {
                Amplify.Auth.signInWithSocialWebUI(
                    AuthProvider.google(),
                    it,
                    { result ->
                        signUpViewModel.handleSocialSignUpResponse(result)
                    },
                    { error ->
                        signUpViewModel.handleSocialSignUpError(error)
                    }
                )
            }

This is onNewIntent() of AuthActivity

    override fun onNewIntent(intent: Intent?) {
        super.onNewIntent(intent)

        if (intent?.data != null && "myapp" == intent.scheme) {
            Amplify.Auth.handleWebUISignInResponse(intent)
//             AWSMobileClient.getInstance().handleAuthResponse(intent)
        }
    }

This is how I am signing out.

            Amplify.Auth.signOut(AuthSignOutOptions.builder().globalSignOut(true).build(),
                {
                    launchMain {
                        progressLD.value = false
                    }
                    sharedPrefs.put(SharedPrefs.PREF_IS_USER_LOGGED_IN, false)
                    _logOutLiveData.postValue(Event(app.applicationContext.getString(R.string.logout_successfully)))
                },
                { error ->
                    launchMain {
                        progressLD.value = false
                    }

                    if (error.cause is AmazonServiceException) {
                        _errorLiveData.postValue(Event((error.cause as AmazonServiceException).errorMessage.orEmpty()))
                    } else {
                        _errorLiveData.postValue(Event(error.localizedMessage.orEmpty()))
                    }
                }
            )

**Comment by gauravbordoloi** [comment] 2020-07-06 12:52
Hello, I am also getting the same issue. Did anyone solved it?

**Comment by TrekSoft** [comment] 2020-07-06 14:02
We haven't gotten to it yet - could you post your activity code and see whether it's hitting the onNewIntent method?

**Comment by gauravbordoloi** [comment] 2020-07-08 05:42
The error is thrown before hitting the onNewIntent method.

**Comment by TrekSoft** [comment] 2020-07-08 15:14
Heads up that we found a way to fix this issue and will be implementing it soon.

**Comment by akoshek** [comment] 2020-08-04 11:02
@TrekSoft Any updates on this issue? I am also getting the same issue.

**Comment by TrekSoft** [comment] 2020-08-04 17:22
Yup, I'm working on the fix this sprint.

**Comment by TrekSoft** [comment] 2020-08-20 19:31
The fix for this has just been released in version 1.2.0. Note that a slight setup change is needed so please follow the updated documentation here to correct your environment: https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/android#update-androidmanifestxml

**Closed by TrekSoft** 2020-08-20 19:31 UTC
Labels: Auth, Bug

**Comment by itslonua** [comment] 2021-11-29 11:28
AuthException{message=Sign-in with web UI failed, cause=com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthInvalidGrantException: invalid_grant, recoverySuggestion=See attached exception for more details

**Comment by Sunsiha** [comment] 2021-12-03 12:58
@itslonua u got any solution?

**Comment by Areebahmed2000** [comment] 2022-03-05 10:25
@Sunsiha u got any solution?

**Comment by ihimanshurawat** [comment] 2022-03-07 11:52
Hey Guys!,

I don't think this got fixed.

However, I override onUserStateChanged in my MainActivity to track the state of the User. These functions do get triggered even after the exception.

 Caused by: com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthInvalidGrantException: invalid_grant

`    override fun onUserStateChanged(details: UserStateDetails?) {
        if (details != null) {
            when (details.userState) {
                UserState.GUEST -> {
                    Log.i(TAG, "user is in guest mode")

                }
                UserState.SIGNED_OUT -> {
                    Log.i(TAG, "user is signed out")
                    removeEmailAddressFromPreferences(userPreferences)
                    removeCustomerIdFromPreferences(userPreferences)
                }
                UserState.SIGNED_IN -> {
                    Log.i(TAG, "user is signed in")
                    getEmailAddressFromAttributes(MobileClient.getAWSMobileClient(),userPreferences)

                }
                UserState.SIGNED_OUT_USER_POOLS_TOKENS_INVALID -> {
                    Log.i(
                        TAG,
                        "need to login again"
                    )

                    removeEmailAddressFromPreferences(userPreferences)
                    removeCustomerIdFromPreferences(userPreferences)
                    Amplify.Auth.signOut(
                        { Log.i("AuthQuickstart", "Signed out successfully")

                        },
                        { Log.e("AuthQuickstart", "Sign out failed", it)
                        })

                }
                UserState.SIGNED_OUT_FEDERATED_TOKENS_INVALID -> {
                    Log.i(
                        TAG,
                        "user logged in via federation, but currently needs new tokens"
                    )
                    removeEmailAddressFromPreferences(userPreferences)
                    removeCustomerIdFromPreferences(userPreferences)
                    Amplify.Auth.signOut(
                        { Log.i("AuthQuickstart", "Signed out successfully")
                        },
                        { Log.e("AuthQuickstart", "Sign out failed", it)
                        })
                }
                else -> {
                    Log.e(TAG, "unsupported")
                }
            }
        }
    }`

**Comment by iAppsBeats** [comment] 2022-05-21 15:30
> However, I override onUserStateChanged in my MainActivity to track the state of the User. These functions do get triggered even after the exception.

Thanks a lot, had the same error, this fixed it 😁
(java code)

```
AWSMobileClient.getInstance().addUserStateListener(new UserStateListener() {
    @Override
    public void onUserStateChanged(UserStateDetails userStateDetails) {
        switch (userStateDetails.getUserState()){
            case SIGNED_IN: {
                // Logged in! Now we can fetch session etc.
                break;
            }
        }
     }
});
Amplify.Auth.signInWithWebUI(this, result -> {}, error -> {});
```

**Comment by samleecampspot** [comment] 2022-06-08 18:33
Although I work in Flutter/Dart, I had an Android specific issue related to signing out using one of the social sign ins (e.g. apple, google, facebook).

My solution had to do with this line for the MainActivity in the AndroidManifest.xml file: ` android:launchMode="singleInstance"`.  We made this refactor to prevent deeplinks from opening up multiple instances of the app.  However, this ended up breaking sign out with a social sign in account for some reason.  Although I did not get to the root cause, reverting the launch mode back to `android:launchMode="singleTop"` fixed the sign out problem.

But this introduces the problem with multiple instances of the app running in the background when opening deeplinks.  I overrode the `onNewIntent()` function in MainActivity to handle deeplinks with the app that's already running, rather than opening a new instance.

```
override fun onNewIntent(intent: Intent) {
        val redirectIntent = Intent(this, HostedUIRedirectActivity::class.java)
        redirectIntent.putExtras(intent)
        startActivity(redirectIntent)
        super.onNewIntent(intent)
    }
```

I hope this helps!
