### ISSUE TITLE
Calling Amplify.Auth.signInWithSocialWebUI throws ClassNotFound exception on v1.3.1

### ISSUE THREAD

**Issue by DanHatesNumbers** [aws-amplify/amplify-android#813] opened 2020-09-09 18:45 UTC
When using version 1.3.1 of Amplify, I see the following error in Logcat when calling Amplify.Auth.signInWithSocialWebUI.

```
2020-09-09 19:42:24.774 17894-17956/uk.co.danhatesnumbers.donext E/AuthQuickstart: AmplifyException {message=Sign in with web UI failed, cause=java.lang.Exception: showSignIn called with HostedUI options in awsconfiguration.json, recoverySuggestion=See attached exception for more details}
2020-09-09 19:42:24.794 17894-17953/uk.co.danhatesnumbers.donext D/AWSMobileClient: Inspecting user state details
2020-09-09 19:42:24.796 17894-17953/uk.co.danhatesnumbers.donext W/AWSMobileClient: Could not check if ACCESS_NETWORK_STATE permission is available.
    java.lang.ClassNotFoundException: android.support.v4.content.ContextCompat
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at com.amazonaws.mobile.client.AWSMobileClient.isNetworkAvailable(AWSMobileClient.java:771)
        at com.amazonaws.mobile.client.AWSMobileClient.getUserStateDetails(AWSMobileClient.java:983)
        at com.amazonaws.mobile.client.AWSMobileClient$5.run(AWSMobileClient.java:845)
        at com.amazonaws.mobile.client.AWSMobileClient$5.run(AWSMobileClient.java:842)
        at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:44)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.ContextCompat" on path: DexPathList[[zip file "/data/app/uk.co.danhatesnumbers.donext-u1DU_Qzm1tA3KJIrGCnfww==/base.apk"],nativeLibraryDirectories=[/data/app/uk.co.danhatesnumbers.donext-u1DU_Qzm1tA3KJIrGCnfww==/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at java.lang.Class.forName(Class.java:379) 
        at com.amazonaws.mobile.client.AWSMobileClient.isNetworkAvailable(AWSMobileClient.java:771) 
        at com.amazonaws.mobile.client.AWSMobileClient.getUserStateDetails(AWSMobileClient.java:983) 
        at com.amazonaws.mobile.client.AWSMobileClient$5.run(AWSMobileClient.java:845) 
        at com.amazonaws.mobile.client.AWSMobileClient$5.run(AWSMobileClient.java:842) 
        at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:44) 
        at java.lang.Thread.run(Thread.java:919) 
```

The underlying cause of this appears to be https://github.com/aws-amplify/aws-sdk-android/issues/2063.

**Comment by jamesonwilliams** [comment] 2020-09-15 23:40
Duplicate of https://github.com/aws-amplify/amplify-android/issues/827;

This issue was resolved in [the 1.3.2 release](https://github.com/aws-amplify/amplify-android/releases/tag/release_v1.3.2). Please try updating your dependency.

**Closed by jamesonwilliams** 2020-09-15 23:40 UTC
Labels: Auth, Bug
