### ISSUE TITLE
Amplify.Auth.signInWithSocialWebUI is automatically tries to log in with last user credentials 

### ISSUE THREAD

**Issue by RoustamManookian** [aws-amplify/amplify-android#1764] opened 2022-06-05 06:58 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line

    implementation 'com.amplifyframework:core:1.28.2'
    implementation 'com.amplifyframework:aws-auth-cognito:1.28.2'

```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

When the app starts and the user clicks the button for signing in with google it automatically signs in with the last user credentials.

### Reproduction steps (if applicable)

 1: install
2: try to log in with google Amplify.Auth.signInWithSocialWebUI()
3: it signs in with the last user credentials
4: clean app cash
5: clean app storage
6: in AWS Cognito global signOut user
7: open the app
8: The same behavior

### Code Snippet

```kotlin
// Put your code below this line.

```Amplify.Auth.signInWithSocialWebUI(
            AuthProvider.google(),
            this,
            {
                Logg.d(TAG, "signInWithSocialWebUI SUCCESS: $it")
                if(viewModel.attachPolicy()) {
                    val username = Amplify.Auth.currentUser.username
                    viewModel.authStatus = AuthStatus.LoggedIn(
                            username,
                            "",
                            "Google"
                        )

                    viewModel.apply {
                        getFCM_Token()
                        savePreferences(username, "", "Google")
                    }
                    Logg.d(TAG,"🎈🎈🎈 Google user logged in ${username}")
                    this.finish()
                }
            },
            {
                Logg.d(TAG, "signInWithSocialWebUI ERROR: ${it.message}")
            }
        )


### Log output

<details>

```
// Put your logs below this line

```

</details>


### amplifyconfiguration.json

~~~
json
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-east-2:###########",
                            "Region": "us-east-2"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-east-2_####",
                        "AppClientId": "12345asdfg",
                        "Region": "us-east-2"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "My_App.auth.us-east-2.amazoncognito.com",
                            "AppClientId": "12345asdfg",
                            "SignInRedirectURI": "scs://callback/",
                            "SignOutRedirectURI": "scs://",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "loginMechanisms": [
                            "EMAIL"
                        ],
                        "signupAttributes": [],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ],
                        "socialProviders": [
                            "GOOGLE"
                        ],
                        "usernameAttributes": [
                            "EMAIL"
                        ]
                    }
                },
                "PinpointAnalytics": {
                    "Default": {
                        "AppId": "123456789asdfghj",
                        "Region": "us-east-1"
                    }
                },
                "PinpointTargeting": {
                    "Default": {
                        "Region": "us-east-1"
                    }
                }
            }
        }
    }
}
~~~

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by div5yesh** [comment] 2022-06-17 22:25
Duplicate of https://github.com/aws-amplify/amplify-android/issues/1287#issuecomment-1132266263

**Closed by div5yesh** 2022-06-17 22:25 UTC
Labels: bug, auth
