### ISSUE TITLE
Amplify dies after Amplify.Auth.deleteUser()

### ISSUE THREAD

**Issue by jpietruszewski** [aws-amplify/amplify-android#2320] opened 2023-03-07 08:52 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin - Coroutines

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line
    implementation "com.amplifyframework:core-kotlin:2.2.1"
    implementation "com.amplifyframework:core:2.2.1"
    implementation "com.amplifyframework:aws-auth-cognito:2.2.1"

```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

After Amplify.Auth.deleteUser() is properly executed every other Amplify.Auth method is not responding after execution.

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by gpanshu** [comment] 2023-03-07 19:17
@jpietruszewski is this the same bug that you are reporting? If yes then please +1 there and respond here and I will close this  issue as duplicate.

**Comment by gpanshu** [comment] 2023-03-13 14:35
Closing as duplicate of #2288 which is in PR right now.

**Closed by gpanshu** 2023-03-13 14:35 UTC
