### ISSUE TITLE
AmplifyTransferService causes IllegalStateException Too many bind requests(999+)

### ISSUE THREAD

**Issue by yaroslav-v** [aws-amplify/amplify-android#2204] opened 2022-12-26 10:26 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

Authentication, Storage

### Gradle script dependencies

<details>

```groovy
// Put output below this line
implementation "com.amplifyframework:core:1.37.10"
implementation "com.amplifyframework:aws-storage-s3:1.37.10"
implementation "com.amplifyframework:aws-auth-cognito:1.37.10"

```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 7.4
------------------------------------------------------------

Build time:   2022-02-08 09:58:38 UTC
Revision:     f0d9291c04b90b59445041eaa75b2ee744162586

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_301 (Oracle Corporation 25.301-b09)
OS:           Mac OS X 10.16 x86_64

```

</details>

### Describe the bug

Hi!

After updating to the latest available v1.37.10 we've started experiencing the following issue:

```
Non-fatal Exception: com.amplifyframework.storage.StorageException
Issue uploading file.

Caused by java.lang.IllegalStateException
Too many bind requests(999+) for service Intent { cmp=com.example.app/com.amplifyframework.storage.s3.service.AmplifyTransferService }

```

The issue happens in all cases on Samsung devices with Android 13 on board.

This isn't a very frequent problem. According to Firebase (for about a week run) - "This issue has 168 events affecting 9 users"

### Reproduction steps (if applicable)

Use amplifyframework v1.37.10

### Code Snippet

```java
// Put your code below this line.

// Initialization in Application class

LogFactory.setLevel(LogFactory.Level.OFF);

Amplify.addPlugin(new AWSCognitoAuthPlugin());
Amplify.addPlugin(new AWSS3StoragePlugin());

AmplifyConfiguration amplifyConfig = AmplifyConfiguration.builder(context)
		.devMenuEnabled(false)
		.build();
Amplify.configure(amplifyConfig, context);



// Uploading, somewhere in the app

DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ", Locale.US);
dateFormat.setTimeZone(TimeZone.getTimeZone("UTC"));

Map<String, String> metadata = new ArrayMap<>(4);
metadata.put("date", dateFormat.format(date));
metadata.put("token", authToken);

StorageUploadFileOptions options =
		StorageUploadFileOptions.builder()
				.accessLevel(StorageAccessLevel.PUBLIC)
				.contentType(mimeType)
				.metadata(metadata)
				.build();

Amplify.Storage.uploadFile(
		"gl_" + new Date().getTime() + "_" + fileName,
		file,
		options,
		result -> {
			// write success logs
		},
		failure -> {
			// write failure logs
		}
);
```

### Log output

<details>

```
// Put your logs below this line

Non-fatal Exception: com.amplifyframework.storage.StorageException
Issue uploading file.

com.amplifyframework.storage.s3.operation.AWSS3StorageUploadFileOperation.lambda$start$0 (AWSS3StorageUploadFileOperation.java:117)
com.amplifyframework.storage.s3.operation.AWSS3StorageUploadFileOperation.$r8$lambda$QI-ZPwBpFWhFV2Ft-tf72m0BK-I (AWSS3StorageUploadFileOperation.java)
com.amplifyframework.storage.s3.operation.AWSS3StorageUploadFileOperation$$InternalSyntheticLambda$1$bd8a937a756305dadd2cf44f21851ad5ccc09f2d4047275e1e9a7036ced8d1bd$0.accept (AWSS3StorageUploadFileOperation.java:8)
com.amplifyframework.storage.s3.configuration.StorageAccessLevelAwarePrefixResolver.resolvePrefix (AWSS3PluginPrefixResolver.kt:64)
com.amplifyframework.storage.s3.operation.AWSS3StorageUploadFileOperation.start (AWSS3StorageUploadFileOperation.java:109)
com.amplifyframework.storage.s3.AWSS3StoragePlugin.uploadFile (AWSS3StoragePlugin.java:367)
com.amplifyframework.storage.s3.AWSS3StoragePlugin.uploadFile (AWSS3StoragePlugin.java:331)
com.amplifyframework.storage.StorageCategory.uploadFile (StorageCategory.java:134)
com.example.app.utils.workmanager.Worker.uploadToAWS (Worker.java:127)
androidx.work.Worker$1.run (Worker.java:86)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1137)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:637)
java.lang.Thread.run (Thread.java:1012)


Caused by java.lang.IllegalStateException
Too many bind requests(999+) for service Intent { cmp=com.example.app/com.amplifyframework.storage.s3.service.AmplifyTransferService }

android.app.ContextImpl.bindServiceCommon (ContextImpl.java:2115)
android.app.ContextImpl.bindService (ContextImpl.java:2024)
android.content.ContextWrapper.bindService (ContextWrapper.java:870)
com.amplifyframework.storage.s3.service.AmplifyTransferService$Companion.bind (AmplifyTransferService.kt:186)
com.amplifyframework.storage.s3.service.AWSS3StorageService.startTransferService (AWSS3StorageService.java:243)
com.amplifyframework.storage.s3.service.AWSS3StorageService.uploadFile (AWSS3StorageService.java:145)
com.amplifyframework.storage.s3.operation.AWSS3StorageUploadFileOperation.lambda$start$0 (AWSS3StorageUploadFileOperation.java:114)
com.amplifyframework.storage.s3.operation.AWSS3StorageUploadFileOperation.$r8$lambda$QI-ZPwBpFWhFV2Ft-tf72m0BK-I (AWSS3StorageUploadFileOperation.java)
com.amplifyframework.storage.s3.operation.AWSS3StorageUploadFileOperation$$InternalSyntheticLambda$1$bd8a937a756305dadd2cf44f21851ad5ccc09f2d4047275e1e9a7036ced8d1bd$0.accept (AWSS3StorageUploadFileOperation.java:8)
com.amplifyframework.storage.s3.configuration.StorageAccessLevelAwarePrefixResolver.resolvePrefix (AWSS3PluginPrefixResolver.kt:64)
com.amplifyframework.storage.s3.operation.AWSS3StorageUploadFileOperation.start (AWSS3StorageUploadFileOperation.java:109)
com.amplifyframework.storage.s3.AWSS3StoragePlugin.uploadFile (AWSS3StoragePlugin.java:367)
com.amplifyframework.storage.s3.AWSS3StoragePlugin.uploadFile (AWSS3StoragePlugin.java:331)
com.amplifyframework.storage.StorageCategory.uploadFile (StorageCategory.java:134)
com.example.app.utils.workmanager.Worker.uploadToAWS (Worker.java:127)
androidx.work.Worker$1.run (Worker.java:86)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1137)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:637)
java.lang.Thread.run (Thread.java:1012)

```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by tylerjroach** [comment] 2023-01-03 16:53
@yaroslav-v In this instance, do you believe that at least 999 transfers have been initiated before the crash is seen? I'm not sure what your use case is for Amplify Storage, and if 999 transfers would be possible in a given app session.

The unbind appears to happen when all transfers are complete, so if a transfer is hanging, and 999+ transfers have been requested, it's possible this is the cause. 

We bind the AmplifyTransferService with each initiated transfer, and even though its the same service, it appears that each `bind` call may increment that counter.

**Comment by yaroslav-v** [comment] 2023-01-04 10:35
@tylerjroach Well, you might be right. However, the issue happens in all cases on Samsung devices with Android 13 on board. Looks like it has some device/system specific flavor.

On the other hand, it isn't really frequent and for the last 3 months there were 9265 events affecting 101 users.

I've checked the data in Firebase for these 3 months and looks like the issue appears on various versions of the library starting from v1.37.1 (didn't use v2).

Regarding the app, it sends an image after a user executed an action on their device. Normally, it shouldn't be frequently then 5-10 events in a minute. So, the number 999+ looks too high even for possible corner cases.

**Comment by yaroslav-v** [comment] 2023-01-05 09:54
Unfortunately, I don't have one. It's all from Firebase logs

**Comment by yaroslav-v** [comment] 2023-01-19 09:10
Hi guys! Are there any news regarding this topic?

**Comment by sdhuka** [comment] 2023-01-19 18:35
@yaroslav-v PR is merged and this fix will be available in the next release.

**Comment by sdhuka** [comment] 2023-01-26 16:29
@yaroslav-v fix is released, please confirm and let us know.

**Closed by sdhuka** 2023-01-26 16:29 UTC
Labels: bug, storage, pending-release
