### ISSUE TITLE
QueryPredicate API - Possible BUG

### ISSUE THREAD

**Issue by KayIlory** [aws-amplify/amplify-android#562] opened 2020-06-05 18:03 UTC
Query predicates currently seem only to work for String equals and contains. All other data types such as float are not working with the API. It returns a zero result for all request with this datatype. Even with `eq`, `lt`, `gt`, `le`, `ge` etc. Running this return no results even though Dynamo has 25 records that meet the set criteria.

Assume a GraphQL with members `longitude` and `latitude`, both of type Float. 

```java
public void getHealthCentresByConsultantFirstPage(
        final Float longitudeStart,
        final Float longitudeEnd,
        final Float latitudeStart,
        final Float latitudeEnd) {
    QueryPredicateGroup predicate =
        HealthCentreConsultant.LONGITUDE.ge(longitudeStart)
            .and(HealthCentreConsultant.LONGITUDE.le(longitudeEnd))
            .and(HealthCentreConsultant.LATITUDE.ge(latitudeStart))
            .and(HealthCentreConsultant.LATITUDE.le(latitudeEnd));
    getHealthCentresByConsultant(
        ModelQuery.list(HealthCentreConsultant.class,
        predicate,
        ModelPagination.firstPage())
    );
}

public void getHealthCentresByConsultant(
        GraphQLRequest<PaginatedResult<HealthCentreConsultant>> request) {
    new Thread(() -> Amplify.API.query(request, response -> {
        if (response.hasData()) {
            for (HealthCentreConsultant healthCentreConsultant : response.getData().getItems()) {
                Timber.d(healthCentreConsultant.toString());
            }
            if (response.getData().hasNextResult()) {
                GraphQLRequest<PaginatedResult<HealthCentreConsultant>> healthCentreConsultantNextPaginatedResult =
                    response.getData().getRequestForNextResult();
            }
        }
    }, error -> {
        Timber.e(error.getCause());
    })).start();
}
```

**Comment by jamesonwilliams** [comment] 2020-06-08 00:28
Closing this as a duplicate of https://github.com/aws-amplify/amplify-android/issues/561. Let's use #561 instead.

**Closed by jamesonwilliams** 2020-06-08 00:28 UTC
Labels: Bug, DataStore
