### ISSUE TITLE
I get UserCancelledException After Login Back

### ISSUE THREAD

**Issue by fauzimubarokk** [aws-amplify/amplify-android#2591] opened 2023-09-21 07:22 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
"com.amplifyframework:aws-auth-cognito:2.11.1"
"com.amplifyframework:core-kotlin:2.11.1"
```

</details>

### Environment information

<details>

```
------------------------------------------------------------
Gradle 7.5.1
------------------------------------------------------------

Build time:   2022-08-05 21:17:56 UTC
Kotlin:       1.6.21
Groovy:       3.0.10


```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/android/#launch-web-ui-sign-in

### Describe the bug

When I call the sign in with web UI function `Amplify.Auth.signInWithWebUI(activity)` after successfully logging out, sometimes I get the `UserCancelledException`. However, I didn't perform the cancel process when the UI starts displaying, but I still encountered that exception.

### Reproduction steps (if applicable)

1. Call the sign out function, and I call the sign-in function when the sign-out process is completed.
```
when (val signOutResult = Amplify.Auth.signOut()) {
  is AWSCognitoAuthSignOutResult.CompleteSignOut -> {
    // Sign Out completed and without errors.
    // Call the sign in function
    try {
      val result = Amplify.Auth.signInWithWebUI(activity)
    } catch (e: AuthException) {
      throw e
    }
  }
  is AWSCognitoAuthSignOutResult.PartialSignOut -> {
    // Sign Out completed with some errors. User is signed out of the device.
    signOutResult.hostedUIError?.let { error ->
    }
    signOutResult.globalSignOutError?.let { error ->
    }
    signOutResult.revokeTokenError?.let { error ->
    }
  }

  is AWSCognitoAuthSignOutResult.FailedSignOut -> {
    // Sign Out failed with an exception, leaving the user signed in.
  }
}
```

2. I get a `UserCancelledException` on the second attempt.

### Log output

<details>

```
 E  UserCancelledException{message=The user cancelled the sign-in attempt, so it did not complete., cause=null, recoverySuggestion=To recover: catch this error, and show the sign-in screen again.}
                                                     	at com.amplifyframework.auth.cognito.RealAWSCognitoAuthPlugin$handleWebUISignInResponse$1.invoke(RealAWSCognitoAuthPlugin.kt:928)
                                                     	at com.amplifyframework.auth.cognito.RealAWSCognitoAuthPlugin$handleWebUISignInResponse$1.invoke(RealAWSCognitoAuthPlugin.kt:878)
                                                     	at com.amplifyframework.statemachine.StateMachine$getCurrentState$1.invokeSuspend(StateMachine.kt:121)
                                                     	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                     	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                     	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
                                                     	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                     	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)

```

</details>

### amplifyconfiguration.json

```json
{
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "ap-southeast-1:c4634124-xxxxxxxxxxx",
                            "Region": "ap-south****"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "ap-southeast-xxxxxx",
                        "AppClientId": "xxxxxxxxx",
                        "Region": "ap-southeast-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "xxxxxx",
                            "AppClientId": "xxxxxxxx",
                            "SignInRedirectURI": "idnapp:****",
                            "SignOutRedirectURI":  "idnapp:****",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        }
                    }
                }
            }
        }
    }
}


```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by tylerjroach** [comment] 2023-09-22 14:19
@fauzimubarokk Can you clarify what is happening when `Amplify.Auth.signInWithWebUI(activity)` is called.

Are you saying:

1. That the web browser is opening and then closing on its own with a following error of `UserCancelledException?
2. That the web browser is opening, you are typing credentials, clicking sign in, and the browser redirects back to the app with `UserCancelledException`?
3. That the web browser is opening, you are clicking the back button, then seeing `UserCancelledException`.

If case 3, this would be the expected behavior.

**Comment by fauzimubarokk** [comment] 2023-09-23 13:14
The web browser doesn't open, and I get `UserCancelledException`, I'm not clicked back button, 

But, if I call `Amplify.Auth.signInWithWebUI(activity)`  without calling the Sign-Out function, I dont have any exception problems.

**Comment by fauzimubarokk** [comment] 2023-09-23 13:14
@tylerjroach

**Comment by ankpshah** [comment] 2023-09-28 02:04
Hello @fauzimubarokk,
   I tried to replicate this issue. It works fine. I am able to Sign Out and then calling Sign In with WebUI successfully when signout is complete.  
   You can try subscribe to Auth Hub events as given here: https://docs.amplify.aws/lib/auth/auth-events/q/platform/android/ 
   Could you check if you have followed all steps here and updated Manisfest file as well: https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/android/

**Comment by ankpshah** [comment] 2023-10-05 22:27
Hello @fauzimubarokk,
   We can debug and figure out what the issue is. Here's link to schedule a time in my calendar: https://prelude.amazon.com/s/4k6EnKFF/eYB2g
   
   I tried exact same steps and it seems to work fine for me.

**Comment by fauzimubarokk** [comment] 2023-10-12 04:00
Hello @ankpshah,  I have already debugged and added breakpoints in the `HostedUIRedirectActivity` class at lines 30 and 42, and it runs without any issues if process is done, but if process is still running and I next breakpoint, sometimes `intent.data` is null.

- Process is running and I skip breakpoint, sometimes I still get `UserCancelledException`.

![image](https://github.com/aws-amplify/amplify-android/assets/101690163/91a488bc-f275-4843-9227-1dddd1ecf328)

- if I wait for the process, I can see the value of `intent.data` and normally without any issues.

![image](https://github.com/aws-amplify/amplify-android/assets/101690163/d6a751e0-7637-4a4b-a890-8451f2393a54)

**Notes** : 
- Maybe that's the reason, when I added a `delay(5000)` before calling `SignInWebUI` after the signout is complete, it runs without any issues.
- Amplify version `2.13.2`

```kotlin
    when (val signOutResult = Amplify.Auth.signOut()) {
      is AWSCognitoAuthSignOutResult.CompleteSignOut -> {
        // Sign Out completed and without errors.
        if (signOutResult.signedOutLocally) {
          delay(5000)
          signIn()
        }
      }

      is AWSCognitoAuthSignOutResult.PartialSignOut -> {
        // Sign Out completed with some errors. User is signed out of the device.
        signOutResult.hostedUIError?.let { error ->
        }
        signOutResult.globalSignOutError?.let { error ->
        }
        signOutResult.revokeTokenError?.let { error ->
        }
      }

      is AWSCognitoAuthSignOutResult.FailedSignOut -> {
      }

**Comment by tylerjroach** [comment] 2023-10-17 21:00
Which browser are you using to sign in?

The error you are referencing will show if an intent is received from you activity that does not have a callbackUri. You have said that the browser is not opening on the sign in call immediately after signing out. 

It almost sounds as if the browser is immediately redirecting back into the application in the same way that would happen if the back button was pressed during sign in.

It seems like there is some race condition here causing an unexpected intent to be received in the activity, so understanding if this is limited to a specific browser could be helpful.

**Comment by gpanshu** [comment] 2023-11-09 19:49
Closing due to inactivity. Please comment here to request for reopening or create a new issue referencing this issue. Thank you.

**Closed by gpanshu** 2023-11-09 19:49 UTC
Labels: pending-response, auth, closing soon

**Comment by tfreeman82** [comment] 2023-12-06 13:47
I'm also having this issue. In my case, it seems to be happening at random sign in attempts and the webview will briefly open then close on its own and return the UserCancelledException. No user interaction at all.

**Comment by tylerjroach** [comment] 2023-12-06 14:20
@tfreeman82 Please open you own ticket with Amplify version used, post information from your `amplifyconfiguration.json` and manifest snippet where the HostedUIRedirectActivity has been added.
