### ISSUE TITLE
AndroidRuntime: java.lang.IllegalStateException: Already resumed

### ISSUE THREAD

**Issue by DaemonZZ** [aws-amplify/amplify-android#2560] opened 2023-08-14 12:42 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin - Coroutines

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line
  com.amplifyframework:aws-auth-cognito:1.32.0
  com.amplifyframework:core-kotlin:0.16.0

```

</details>

### Environment information

<details>

```
# Put output below this line
Gradle 7.4
------------------------------------------------------------

Build time:   2022-02-08 09:58:38 UTC
Revision:     f0d9291c04b90b59445041eaa75b2ee744162586

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_381 (Oracle Corporation 25.381-b09)
OS:           Windows 11 10.0 amd64


```

</details>

### Describe the bug

I am using Amplify Authentication library. My application crash  sometimes when I try to submit MFA otp

```java
 override suspend fun submitMfaCode(
        medium: AmplifyVerificationMedium,
        code: String
    ): AmplifyAuthInterface.SignInState {
        return try {
            Timber.d("submitMfaCode: $medium, $code")
            val confirmationCode = getConfirmCodeValue(medium, code)
            val result = amplifyAuth.confirmSignIn(confirmationCode)
            Timber.d("submitMfaCode: result: $result")
            if (result.isSignInComplete) {
                AmplifyAuthInterface.SignInState.Success
            } else {
                // Code was not valid, so still in this state
                AmplifyAuthInterface.SignInState.InvalidCode
            }
        } catch (e: AuthException) {
            handleException(e)
        } catch (e: IllegalStateException) {
            Timber.e("handleException: ${e.cause}")
            AmplifyAuthInterface.SignInState.UnknownFailure
        }
    }
```

I found there are some crash happening in the Amplify library. Here is the crash output:

> 08-08 01:48:20.612 10425 27555 29956 E AndroidRuntime: FATAL EXCEPTION: Thread-69
08-08 01:48:20.612 10425 27555 29956 E AndroidRuntime: Process: com.example.abc, PID: 27555
08-08 01:48:20.612 10425 27555 29956 E AndroidRuntime: java.lang.IllegalStateException: Already resumed
08-08 01:48:20.612 10425 27555 29956 E AndroidRuntime: at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuationJvm.kt:44)
08-08 01:48:20.612 10425 27555 29956 E AndroidRuntime: 	at com.amplifyframework.kotlin.auth.KotlinAuthFacade$confirmSignIn$2$1.accept(KotlinAuthFacade.kt:120)
08-08 01:48:20.612 10425 27555 29956 E AndroidRuntime: 	at com.amplifyframework.kotlin.auth.KotlinAuthFacade$confirmSignIn$2$1.accept(KotlinAuthFacade.kt:49)
08-08 01:48:20.612 10425 27555 29956 E AndroidRuntime: 	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$6.lambda$onResult$0(AWSCognitoAuthPlugin.java:465)
08-08 01:48:20.612 10425 27555 29956 E AndroidRuntime: 	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$6$$ExternalSyntheticLambda0.call(Unknown Source:4)
08-08 01:48:20.612 10425 27555 29956 E AndroidRuntime: 	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$23.onError(AWSCognitoAuthPlugin.java:1267)

I went to check the library code to see where this crash happening. I found it is happening in below code where continuation gets called multiple time:

```java
 override suspend fun confirmSignIn(
        confirmationCode: String,
        options: AuthConfirmSignInOptions
    ): AuthSignInResult {
        return suspendCoroutine { continuation ->
            delegate.confirmSignIn(
                confirmationCode,
                options,
                { continuation.resume(it) },
                { continuation.resumeWithException(it) }
            )
        }
    }
```
Could you tell me what to do to prevent this error happening as it crashing my app.

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by gpanshu** [comment] 2023-08-21 16:45
Can you use V2 version of the Amplify library for Android and see if you can reproduce the issue? If you are able to I would also ask that you add the logs from logcat after adding `Amplify.addPlugin(AndroidLoggingPlugin(LogLevel.VERBOSE))` before you add the authentication plugin in your application class.

**Comment by doanpt** [comment] 2023-08-23 02:24
We've tried v2 and the crash was not observed, but another issue I raised on above comment.. so we are stuck with both of v1 and v2.

**Comment by gpanshu** [comment] 2023-08-23 06:20
Ok since this issue was resolved I am closing this. We are tracking the srp issue separately and your active support on helping fix is very much appreciated.

**Closed by gpanshu** 2023-08-23 06:20 UTC
Labels: bug, pending-response, auth
