### ISSUE TITLE
Facebook denies aws pool URL as Website in facebook console

### ISSUE THREAD

**Issue by chirag-ss** [aws-amplify/amplify-android#1622] opened 2022-01-03 09:57 UTC
**Describe the bug**
I have integrated the Facebook login with Amplify HostedUI in my app. I have set up the Facebook console app as per the document of Amplify SDK.
**Document Link:** https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/android/#configure-auth-category

Our Facebook app was disabled due to the URL(user pool domain with the /oauth2/idpresponse endpoint) that we add as a Website URL (As per Amplify SDK Document).
**Website URL in Document:** https://\<your-user-pool-domain>/oauth2/idpresponse
**Our app URL:** https://ss-v2-stg.auth.us-west-2.amazoncognito.com/oauth2/idpresponse

According to Facebook, The Website URL is broken. We were able to do Facebook Login earlier with the same URL. Now the Facebook app is disabled so we can't do the Facebook login.

Please let us know what can we do in this case?

**Which AWS service(s) are affected?**
implementation 'com.amplifyframework:core:1.21.0'
implementation 'com.amplifyframework:aws-auth-cognito:1.21.0'

**Screenshots**
Attached is the screenshot of the mail from Facebook & the screenshot sent by Facebook.
![Screen Shot 2022-01-03 at 3 13 34 PM](https://user-images.githubusercontent.com/47347241/147917645-64606cd6-c700-4ded-afa3-1d4f7e7d0089.png)

<img width="1792" alt="mp5LOV" src="https://user-images.githubusercontent.com/47347241/147917144-f80a742b-1814-4953-a235-c624f3c42c10.png">

**Comment by chirag-ss** [comment] 2022-01-06 10:17
Hi @eeatonaws,
As you suggested, I have used the URL with the Hosted UI Endpoint by appending `/oauth2/idpresponse` but that URL is also not working.
https://shearsharedev52533f64-52533f64-dev.auth.us-west-2.amazoncognito.com/oauth2/idpresponse

In our user pool domain section, I can see the below Domain. I tried appending `/oauth2/idpresponse` but it is also not working.
**Domain**: https://ss-v2-stg.auth.us-west-2.amazoncognito.com
**URL**: https://ss-v2-stg.auth.us-west-2.amazoncognito.com/oauth2/idpresponse

Attached is the screenshot for the domain section. Let me know if you are referring to any other section in the console.
![Screen Shot 2022-01-06 at 2 27 39 PM](https://user-images.githubusercontent.com/47347241/148366145-88450cc9-3439-42f0-9f33-9f9735efc06e.png)

I am able to get the Hosted UI URL from the `App Client Settings` of the AWS console which is working fine. Let me know if I have to modify this URL or I can use it directly in the Facebook App Console.
**Hosted UI Link from Console:** https://ss-v2-stg.auth.us-west-2.amazoncognito.com/login?client_id=addhh5kgf4i5rogkj3rql295p&response_type=code&scope=aws.cognito.signin.user.admin+email+openid+phone+profile&redirect_uri=http://localhost:3000/

**Comment by eeatonaws** [comment] 2022-01-06 22:26
Hi @chirag-ss. The user pool domain shown in the Cognito console should be the same as the hosted UI endpoint printed out by `amplify status`. Please run `amplify pull` and then `amplify status` to verify if the hosted UI endpoint now matches the user pool domain. The URL https://ss-v2-stg.auth.us-west-2.amazoncognito.com/oauth2/idpresponse looks correct based on your user pool domain. Could you verify that you used the user pool domain shown in the Cognito console when following steps 5, 7, and 11 from the [Amplify social sign-in documentation](https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/android/#configure-auth-category)?

**Comment by chirag-ss** [comment] 2022-01-07 09:32
Hi @eeatonaws,
I have again run the `amplify pull` and then `amplify status` to verify the hosted UI endpoint as you suggested but I am still getting the same result. (Attached is the screenshot for it)
![Screen Shot 2022-01-07 at 2 01 59 PM](https://user-images.githubusercontent.com/47347241/148521217-09cc5dd2-b94b-4fe9-9975-699ad35222d3.png)

I have also verified the steps 5, 7, and 11 from the [Amplify social sign-in documentation](https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/android/#configure-auth-category). (Attached the screenshots for it as well)

**Step 5:**
![Screen Shot 2022-01-07 at 2 09 03 PM](https://user-images.githubusercontent.com/47347241/148521884-fdc02b62-f077-4a16-a493-7c66692b7490.png)

**Step 7:**
![Screen Shot 2022-01-07 at 2 38 51 PM](https://user-images.githubusercontent.com/47347241/148522133-b96c43e2-87c7-405d-ab9f-3b8385c7befd.png)

**Step 11:**
![Screen Shot 2022-01-07 at 2 40 06 PM](https://user-images.githubusercontent.com/47347241/148522208-1588f93a-f26e-493c-b94e-ca3c9c26dfea.png)

Can I resolve this issue by creating a new Amplify project or by updating the auth in the existing amplify app? If yes, then can you please provide me with the documents or steps to perform it?

**Comment by chirag-ss** [comment] 2022-01-12 14:38
Hi @eeatonaws,
Any update on this?

**Comment by eeatonaws** [comment] 2022-01-12 21:35
Hi @chirag-ss, we are still looking into the issue and will let you know when we have an update.

**Comment by eeatonaws** [comment] 2022-01-13 17:27
Hi @chirag-ss. In one of the screenshots you shared, it says that Facebook "disabled this app for violating the Facebook Platform Policies". Could you check if there are other reasons besides the broken website URL that Facebook disabled your app? If there are no other reasons for the app being disabled or if resolving the other reasons still produces the error, then please try removing auth from your project (`amplify remove auth`) and then following the [Amplify social sign in steps](https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/android/) again, using `amplify add auth` to configure the Facebook sign in and if possible, creating a new Facebook app, as I am unable to reproduce the issue when following the Amplify social sign in steps.

**Comment by chirag-ss** [comment] 2022-01-14 09:59
Hi @eeatonaws,
You are right! The broken URL isn't the reason that Facebook blocked the App. It was blocked due to an older Facebook SDK was being used (for sharing) in our App. (I get to know the reason when I filed the **first appeal** to facebook to enable the app)

To resolve that issue, I have updated my production app with the latest Facebook SDK & after that warning for that issue was also removed from the Facebook console. 

Then I filed the **second appeal** to enable the app again but the app gone under review process & they prompted this issue.

What you are suggesting might be the temporary solution because creating a new Facebook App OR removing/adding auth won't stop the Facebook Review process. This issue might happen again if Facebook will review the app again after enabling it.

I have also tried to create a new Amplify project but it also has the same issue of generating broken WebSite URL. Please see the below Endpoint URLs.
**Hosted UI Endpoint:** https://ss-v2-stg-stage.auth.us-west-2.amazoncognito.com/
**Test Your Hosted UI Endpoint:** https://ss-v2-stg-stage.auth.us-west-2.amazoncognito.com/login?response_type=code&client_id=7sbrimlvl6huui52crs4ga8ku3&redirect_uri=shearshare://callback/
**Website URL for Facebook:** https://ss-v2-stg-stage.auth.us-west-2.amazoncognito.com/oauth2/idpresponse

<img width="1084" alt="Screenshot 2022-01-07 at 9 22 16 PM" src="https://user-images.githubusercontent.com/47347241/149494868-170f01c5-5841-40cd-aade-07fea53fa74f.png">

Let me know if you find any issue in my amplify project creation which might be the reason to generate broken URL. 
For now, I'll try for the solutions you provided. Thanks! :)

**Comment by eeatonaws** [comment] 2022-01-14 15:15
Hi @chirag-ss. When you say you are having the same issue of a broken website URL with a new Amplify project, are you receiving an email from Facebook saying the URL is broken (like in your original comment on this issue)? I'm able to open the link that says "Test Your Hosted UI Endpoint" and it opens correctly, which indicates there could be a problem with the app configuration in Facebook (specifically, the part of the [Amplify social sign in docs](https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/android/#configure-auth-category) starting with "You need to now inform your auth provider of this URL").

**Comment by chirag-ss** [comment] 2022-01-14 16:01
Hi @eeatonaws, 
Apologies for not mentioning that I haven't configured the new Amplify project with our Facebook App yet. I just created new project to check that the URL works fine OR not. In my [comment](https://github.com/aws-amplify/amplify-android/issues/1622#issuecomment-1012972561), If you click on **Website URL for Facebook** then it still leads to the SignIn page which gives an error of `Invalid state` which in turn Facebook will reject considering it as a Broken URL.
![Screen Shot 2022-01-14 at 9 03 27 PM](https://user-images.githubusercontent.com/47347241/149543417-c7b775f6-7bc0-42fa-bff4-1494fe90cd1a.png)

We do not want to switch to the new user pool now(I created it for testing purposes only). We have set up our project with the below AWS pool & wanted the Facebook login to work with it.
![stage v2 pool](https://user-images.githubusercontent.com/47347241/149544274-5e1d7932-aa67-4c80-b15d-5054e92b6f4c.png)

Same as the **URL** in this [comment](https://github.com/aws-amplify/amplify-android/issues/1622#issuecomment-1006444519), The new Amplify project also produces the SiteURL with the `Invalid state` error. Can we fix it for the this user pool?

Thanks!

**Comment by gpanshu** [comment] 2022-01-14 18:46
@chirag-ss are you doing amplify update auth to update the fb app id and secret?

**Comment by chirag-ss** [comment] 2022-01-15 10:24
Hi @gpanshu , 
As I have [mentioned earlier](https://github.com/aws-amplify/amplify-android/issues/1622#issuecomment-1004656604) in this thread, We are using the user pool which is set up by our backend engineers. We have created Amplify project to get the `amplifyconfiguration.json` & replaced the user pool details (in `amplifyconfiguration.json`) with the pool details provided by our BE eng. 
In that user pool's Identity provide section, we have configured the `fb app id` & `secret`. Please check the below screenshot for it.
![Screen Shot 2022-01-15 at 3 41 56 PM](https://user-images.githubusercontent.com/47347241/149618136-af8a4a6e-797a-4b26-9be1-5f6fc2eb34d3.png)

FB login was working fine for the last 5 months with that `amplifyconfiguration.json` until the Facebook app has gone under the review process.

**Comment by gpanshu** [comment] 2022-01-16 13:55
@chirag-ss I am not sure how we can proceed in this considering it works us using the sample instructions provided. Would you be able to create a new FB app, keep your app as and configure the new fb app secret and id and see if that works. Perhaps it is something to do with that particular FB app and not Amplify?

**Closed** 2022-02-11 15:02 UTC
Labels: pending-response, auth, closing soon
