### ISSUE TITLE
[Flutter support] Turning network off in a datastore app crashes it.

### ISSUE THREAD

**Issue by Amplifiyer** [aws-amplify/amplify-android#1022] opened 2020-12-03 02:13 UTC
When a flutter datastore app loses network connection, it crashes with the errors in the attached logs
 [network on -> off.txt](https://github.com/aws-amplify/amplify-android/files/5633220/network.on.-.off.txt)

At the time the network was turned off, the mutation queue was empty.

Starting the app in a no network state causes these errors and bringing network back doesn't start the subscriptions.
[network off.txt](https://github.com/aws-amplify/amplify-android/files/5633224/network.off.txt)

**Comment by jamesonwilliams** [comment] 2020-12-03 02:19
Thanks, @Amplifiyer. Looks like a duplicate of https://github.com/aws-amplify/amplify-android/issues/541.

**Closed by jamesonwilliams** 2020-12-03 02:19 UTC
