### ISSUE TITLE
Enabling Sorting ASC/DSC in Amplify.API

### ISSUE THREAD

**Issue by KayIlory** [aws-amplify/amplify-android#859] opened 2020-09-25 11:43 UTC
I see sorting has been introduced on the Amplify.DataStore. Is it possible to have this introduced on API calls as well. Appreciate the assistance with this..

**Comment by jamesonwilliams** [comment] 2020-09-28 04:15
Duplicate of https://github.com/aws-amplify/amplify-android/issues/837.

**Closed by jamesonwilliams** 2020-09-28 04:15 UTC
Labels: API, Feature Request
