### ISSUE TITLE
Sign in with social web UI throws this error

### ISSUE THREAD

**Issue by gauravbordoloi** [aws-amplify/amplify-android#625] opened 2020-07-06 13:13 UTC
Calling the below function:

```kotlin
Amplify.Auth.signInWithSocialWebUI(
    AuthProvider.facebook(),
    requireActivity(),
    { result -> Logger.d(result) },
    { error -> Logger.e(error, "AuthQuickstart") }
)
```
Throws below error:

```console
AuthQuickstart : AmplifyException {message=Sign in with web UI failed, cause=com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthNavigationException: user cancelled, recoverySuggestion=See attached exception for more details}
2020-07-06 18:40:00.666 1050-1612/in.homedrop.delivery E/PRETTY_LOGGER: │ 	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$13.onError(AWSCognitoAuthPlugin.java:1)
2020-07-06 18:40:00.666 1050-1612/in.homedrop.delivery E/PRETTY_LOGGER: │ 	at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
2020-07-06 18:40:00.666 1050-1612/in.homedrop.delivery E/PRETTY_LOGGER: │ 	at com.amazonaws.mobile.client.internal.InternalCallback.onError(InternalCallback.java:67)
2020-07-06 18:40:00.666 1050-1612/in.homedrop.delivery E/PRETTY_LOGGER: │ 	at com.amazonaws.mobile.client.AWSMobileClient$25$1$3.run(AWSMobileClient.java:2954)
2020-07-06 18:40:00.666 1050-1612/in.homedrop.delivery E/PRETTY_LOGGER: │ 	at java.lang.Thread.run(Thread.java:919)
2020-07-06 18:40:00.666 1050-1612/in.homedrop.delivery E/PRETTY_LOGGER: │ Caused by: com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthNavigationException: user cancelled
2020-07-06 18:40:00.666 1050-1612/in.homedrop.delivery E/PRETTY_LOGGER: │ 	at com.amazonaws.mobileconnectors.cognitoauth.AuthClient$4.onNavigationEvent(AuthClient.java:624)
2020-07-06 18:40:00.666 1050-1612/in.homedrop.delivery E/PRETTY_LOGGER: │ 	at androidx.browser.customtabs.CustomTabsClient$2$1.run(CustomTabsClient.java:288)
2020-07-06 18:40:00.666 1050-1612/in.homedrop.delivery E/PRETTY_LOGGER: │ 	at android.os.Handler.handleCallback(Handler.java:883)
2020-07-06 18:40:00.666 1050-1612/in.homedrop.delivery E/PRETTY_LOGGER: │ 	at android.os.Handler.dispatchMessage(Handler.java:100)
2020-07-06 18:40:00.666 1050-1612/in.homedrop.delivery E/PRETTY_LOGGER: │ 	at android.os.Looper.loop(Looper.java:214)
2020-07-06 18:40:00.666 1050-1612/in.homedrop.delivery E/PRETTY_LOGGER: │ 	at android.app.ActivityThread.main(ActivityThread.java:7710)
2020-07-06 18:40:00.666 1050-1612/in.homedrop.delivery E/PRETTY_LOGGER: │ 	at java.lang.reflect.Method.invoke(Native Method)
2020-07-06 18:40:00.666 1050-1612/in.homedrop.delivery E/PRETTY_LOGGER: │ 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
2020-07-06 18:40:00.666 1050-1612/in.homedrop.delivery E/PRETTY_LOGGER: │ 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

This error is being thrown before `onNewIntent` gets called. I have also added `android:launchMode="singleInstance"` to the activity, but still get the same error.

**Comment by jamesonwilliams** [comment] 2020-07-08 06:33
@gauravbordoloi Please include:
1. The contents of your `amplifyconfiguration.json` (please scrub out any credentials with \*\*\* marks.)
2. Your full code sample, including where you have implemented [these suggestions](https://github.com/aws-amplify/aws-sdk-android/issues/871#issuecomment-608547360)
3. The version of Amplify you are using, include your declarations in `build.gradle`.
4. The contents of your `AndroidManifest.xml`.

[Here are some tips on formatting code in Markdown](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).

**Comment by gauravbordoloi** [comment] 2020-07-10 01:58
> amplifyconfiguration.json

`{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/2.0",
                "Version": "1.0",
                "IdentityManager": {
                    "Default": {
                        "PoolId": "****",
                        "Region": "ap-south-1"
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "****",
                        "AppClientId": "****",
                        "AppClientSecret": "****",
                        "Region": "ap-south-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "homedrop.auth.ap-south-1.amazoncognito.com",
                            "AppClientId": "****",
                            "SignInRedirectURI": "homedrop://callback",
                            "SignOutRedirectURI": "homedrop://signout",
                            "Scopes": [
                                "email",
                                "openid",
                                "profile",
                                "phone"
                            ]
                        }
                    }
                }
            }
        }
    },
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "amplifyDatasource": {
                    "endpointType": "GraphQL",
                    "endpoint": "****",
                    "region": "ap-south-1",
                    "authorizationType": "API_KEY",
                    "apiKey": "****"
                }
            }
        }
    }
}`

> code sample

`Amplify.Auth.signInWithSocialWebUI(
            AuthProvider.facebook(),
            this,
            { result -> Logger.e("AuthQuickstart", result.toString()) },
            { error -> Logger.e(error, "AuthQuickstart") }
        )`

`override fun onNewIntent(intent: Intent?) {
        super.onNewIntent(intent)
        Logger.d(intent?.data)
        Logger.d(intent?.data?.scheme)
        if (intent == null || intent.scheme == null) {
            return
        }
        if(intent.data!!.scheme!! == "homedrop") {
            Logger.d("handled web ui response")
            Amplify.Auth.handleWebUISignInResponse(intent)
        }
    }`

> amplify sdk

`implementation 'com.amplifyframework:core:1.0.0'
    implementation 'com.amplifyframework:aws-auth-cognito:1.0.0'
    implementation 'com.amplifyframework:aws-analytics-pinpoint:1.0.0'
    implementation 'com.amplifyframework:aws-datastore:1.0.0'
    implementation 'com.amplifyframework:aws-api:1.0.0'`

> Manifest

`<activity android:name=".BaseActivity"
            android:launchMode="singleInstance">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />


                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />


                <data android:scheme="homedrop" />
            </intent-filter>
        </activity>`

**Comment by jamesonwilliams** [comment] 2020-07-10 04:50
@gauravbordoloi https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by jpignata** [comment] 2020-07-16 22:27
Looks to be related to https://github.com/aws-amplify/aws-sdk-android/issues/871

**Comment by TrekSoft** [comment] 2020-07-20 18:23
Yeah, this is a duplicate of #552 - will track progress there.

**Closed by TrekSoft** 2020-07-20 18:23 UTC
Labels: Auth, Bug
