### ISSUE TITLE
Android's mutation selection set is incompatible with iOS' subscription handling

### ISSUE THREAD

**Issue by jamesonwilliams** [aws-amplify/amplify-android#995] opened 2020-11-25 06:25 UTC
From @Amplifiyer: 

While testing the sync between local and remote, @jamesonwilliams and I found some weird behavior between how it works in iOS and Android. The selection set of the create mutations in iOS seem to include the full nested model fields, while in android it’s only the ID. So for instance if I create two mutations from AppSync as follows:

```graphql
mutation OnlyIdMutation {
  createPost(input: {blogID: "6a83a3b4-2b82-4dfa-8b58-5e32326865a2", rating: 10, title: "Remote blog 6"}) {
    _deleted
    _lastChangedAt
    _version
    blogID
    created
    createdAt
    id
    rating
    title
    updatedAt
    blog {
      id
    }
  }
}
```

and

```graphql
mutation FullNestedModelMutation {
  createPost(input: {blogID: "6a83a3b4-2b82-4dfa-8b58-5e32326865a2", rating: 10, title: "Remote blog 6"}) {
    _deleted
    _lastChangedAt
    _version
    blogID
    created
    createdAt
    id
    rating
    title
    updatedAt
    blog {
      id
      updatedAt
      name
      createdAt
      _version
      _lastChangedAt
      _deleted
    }
  }
}
```

Both are successful on Android, but only the later works on iOS. The first one will result in some GraphQL errors on the iOS client:

```json
{
  "id": "2ACF986E-7607-4CD7-AEE3-148F34B01183",
  "type": "data",
  "payload": {
    "data": {
      "onCreatePost": {
        "id": "909fccc6-7ad3-4408-8b49-23616123413e",
        "created": null,
        "rating": 3,
        "title": "Post 2 android\t",
        "blog": null,
        "__typename": "Post",
        "_version": 1,
        "_deleted": null,
        "_lastChangedAt": 1606251462643
      }
    },
    "errors": [
      {
        "message": "Cannot return null for non-nullable type: 'String' within parent 'Blog' (/onCreatePost/blog/name)",
        "path": [
          "onCreatePost",
          "blog",
          "name"
        ]
      },
      {
        "message": "Cannot return null for non-nullable type: 'Int' within parent 'Blog' (/onCreatePost/blog/_version)",
        "path": [
          "onCreatePost",
          "blog",
          "_version"
        ]
      },
      {
        "message": "Cannot return null for non-nullable type: 'AWSTimestamp' within parent 'Blog' (/onCreatePost/blog/_lastChangedAt)",
        "path": [
          "onCreatePost",
          "blog",
          "_lastChangedAt"
        ]
      }
    ]
  }
}
```

------------

@jamesonwilliams notes: We have a [toggle for this behavior](https://github.com/aws-amplify/amplify-android/blob/main/aws-api-appsync/src/main/java/com/amplifyframework/api/aws/LeafSerializationBehavior.java#L21), when making GraphQL requests. The DataStore category [only includes requests IDs from children](https://github.com/aws-amplify/amplify-android/blob/main/aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/DataStoreGraphQLRequestOptions.java#L63), and the [API category requests all fields](https://github.com/aws-amplify/amplify-android/blob/main/aws-api/src/main/java/com/amplifyframework/api/aws/ApiGraphQLRequestOptions.java#L56).

@jamesonwilliams  & @richardmcclellan are not aware of any good reason why it _needs_ to be this way.

----------

@drochetti notes: It’s breaking in iOS most likely because the underlying model is required or has required properties. Swift is very strict when deserializing JSON since types declared as required must be provided at creation time. You can’t do `name: String!` and then not provide it when constructing the object.

**Comment by HuiSF** [comment] 2021-09-17 16:37
This causes https://github.com/aws-amplify/amplify-flutter/issues/663
This makes realtime data syncing impossible when trigger model change from Android, iOS devices will never receive the update until restart the App.

**Comment by changxu0306** [comment] 2021-09-21 06:45
@HuiSF discovered that amplify-android has a bug that the `SelectionSet` class never generates GraphQL document correctly, as the `getModelFields` for Flutter uses `ModelSchemaRegistry` as singleton but it actually is not a singleton so it cannot retrieve related model schema. 

On Android side, it worth a look at `SelectionSet` class to figure out a possible fix.

**Comment by HuiSF** [comment] 2021-09-21 17:46
Thanks for looking into it @changxu0306 .

I found the same issue as you stated, this singleton issue should've been fixed with my PR https://github.com/aws-amplify/amplify-android/pull/1459 .

The difference on `SelectionSet` between amplify-android and amplify-ios is that amplify-ios doesn't list all fields for nested models as this setting: https://github.com/aws-amplify/amplify-android/blob/35f3b25a66154cc9dd83e4be15d52a50a8c69b1b/aws-api-appsync/src/main/java/com/amplifyframework/api/aws/SelectionSet.java#L360-L363

amplify-android DataStore sets default leaf node parsing level as 1, so it lists only `id` fields for nested models in a GraphQL document. I suppose this behavior should be changed to align with amplify-ios so the DataStore plugin can work correctly cross platforms.

**Comment by eeatonaws** [comment] 2022-06-09 19:23
Duplicate of #1772

**Closed by eeatonaws** 2022-06-09 19:23 UTC
Labels: bug, datastore, flutter, p1
