### ISSUE TITLE
Neither Cognito Identity or Cognito UserPool was used

### ISSUE THREAD

**Issue by planasmultimedia** [aws-amplify/amplify-android#566] opened 2020-06-07 17:56 UTC
If i execute in CLI: `amplify status`, I got the following settings:
 Category | Resource name      | Operation | Provider plugin   |
| -------- | ------------------ | --------- | ----------------- |
| Function | Music2AllLambdas   | No Change | awscloudformation |
| Auth     | cognito... | No Change | awscloudformation |
| Api      | ApiRest            | No Change | awscloudformation |
| Api      | Music2AllAPI       | No Change | awscloudformation |
| Storage  | musicallsongimages | No Change | awscloudformation |

```
E/bakeanoMessage: Amplify adding plugins Exception: Failed to instantiate AWSMobileClient
    AmplifyException {message=Failed to instantiate AWSMobileClient, cause=java.lang.RuntimeException: Neither Cognito Identity or Cognito UserPool was used. At least one must be present to use AWSMobileClient., recoverySuggestion=See attached exception for more details}
        at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.configure(AWSCognitoAuthPlugin.java:87)
        at com.amplifyframework.core.category.Category.configure(Category.java:13)
        at com.amplifyframework.core.Amplify.configure(Amplify.java:17)
        at com.amplifyframework.core.Amplify.configure(Amplify.java:1)
        at com.example.music2all.MyApplication.onCreate(MyApplication.java:26)
```

`app/build dependencies`: 
```
implementation ('com.amazonaws:aws-android-sdk-mobile-client:2.16.12') { transitive = true; }
    implementation 'com.amplifyframework:core:1.0.0'
    implementation 'com.amplifyframework:aws-storage-s3:1.0.0' // For S3 storage
    implementation 'com.amplifyframework:aws-auth-cognito:1.0.0'
    implementation 'com.amazonaws:aws-android-sdk-auth-userpools:2.16.12' //For UserPoolsSignIn
    implementation 'com.amazonaws:aws-android-sdk-core:2.16.12'
    implementation 'com.amazonaws:aws-android-sdk-cognito:2.16.12'
    implementation 'com.amazonaws:aws-android-sdk-s3:2.16.12'


    implementation 'com.amazonaws:aws-android-sdk-apigateway-core:2.16.12'
```

`MyApplication`:
```
    public void onCreate() {
        super.onCreate();

        try {
            Amplify.addPlugin(new AWSCognitoAuthPlugin());
            Amplify.configure(getApplicationContext());
            Log.d("My Application", "AMPLIFY INITIALIZED ----------------");
        } catch (AmplifyException e) {
            Log.e("bakeanoMessage", "Amplify adding plugins Exception: " + e.getMessage(), e);
        }
    }
```

I don't know what i'm missing here, everything is configured following the tutorials and i spend so many hours trying to fix this. Please help

**Comment by jamesonwilliams** [comment] 2020-06-08 00:25
Hi @planasmultimedia! 
```
Neither Cognito Identity or Cognito UserPool was used. At least one must be present to use AWSMobileClient.
```

What's the current contents of you `amplifyconfiguration.json`? Do you also have an `awsconfiguration.json`?  (Please reply here with `XXX` for any sensitive _values_ in those configs.)

In your `build.gradle`, you include Amplify libraries, but then you also include the low-level SDK directly. Is this to support some existing, unrelated code? Based on the code you've shown in `MyApplication`, you should only need `implementation 'com.amplifyframework:aws-auth-cognito:1.0.0'`.

**Comment by Scarlett13** [comment] 2020-06-15 15:55
Hey, try to look to this answer:

https://github.com/aws-amplify/amplify-android/issues/549#issuecomment-637100313

**Comment by jamesonwilliams** [comment] 2020-06-17 05:03
Thanks @Scarlett13! Closing this #566 as a duplicate of #549.

**Closed by jamesonwilliams** 2020-06-17 05:03 UTC
Labels: Auth, Clarification Needed, Closing Soon, Usage Question
