### ISSUE TITLE
Is there a way to modify the Host header when signing an API request using IAM auth?

### ISSUE THREAD

**Issue by ekmwilson** [aws-amplify/amplify-android#1328] opened 2021-05-20 16:37 UTC
Description:
My team is using domain fronting for Akamai where our Akamai URL maps to an API GW endpoint. We're leveraging Amplify's API methods to call the Akamai endpoint with IAM auth. This creates an issue while performing the SIGv4 signing as we get the following error when targeting our Akamai endpoint: 

`The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.`

To get around this we need to customize the Host header for the signing to be the API GW endpoint instead of the Akamai one. Is it possible to customize this value for the signing using the SDK?
 
Amplify Version:
implementation 'com.amplifyframework:aws-api:1.6.8'

Code Sample:
amplifyConfiguration.json sample:

```
{
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "api": {
    "plugins": {
      "awsAPIPlugin": {
        "API_NAME": {
          "endpointType": "REST",
          "endpoint": "https://akamai...",
          "region": "us-east-2",
          "authorizationType": "AWS_IAM"
        }
      }
    }
  }
}
```

```
RestOptions options = RestOptions.builder()
                .addPath(PATH)
                .addBody(gson.toJson(REQUEST_BODY).getBytes())
                .build();

Amplify.API.post(API_NAME,
                options,
                this::handleResponse,
                error -> handleError(error));
```

**Comment by ekmwilson** [comment] 2021-05-26 01:40
Thanks for your response @richardmcclellan . To be clear, we're not trying to customize the headers of the API request, we're trying to "overwrite" the Host header that is used for the automatic signing as we're using IAM auth.  

There's a few places the host header is referenced but taking a quick look at the code I think we're looking for something that would allow us to modify the host property [here](https://github.com/aws-amplify/aws-sdk-android/blob/e31564c594212c825c53a3272ca6d9120d69d096/aws-android-sdk-core/src/main/java/com/amazonaws/auth/AWS4Signer.java#L335) or somewhere similar.

**Comment by richardmcclellan** [comment] 2021-06-23 02:02
Closing as a duplicate of https://github.com/aws-amplify/amplify-android/issues/1328.   Please refer to that ticket for progress on this feature!

**Closed by richardmcclellan** 2021-06-23 02:02 UTC
Labels: API, Feature Request
