### ISSUE TITLE
Amplify library on Android is missing the detection of "AlreadyConfiguredException" for Kotlin/Java users

### ISSUE THREAD

**Issue by somardk** [aws-amplify/amplify-android#1651] opened 2022-02-03 18:53 UTC
**Describe the bug**
I am using Kotlin to Authenticate a user login via Amazon Cognito in a login page on Android device. Relaunching the login page would crash the whole app.

**To Reproduce**
In my login page's onCreate(), I perform the login. Firs time, it works. If I close the app and try to relaunch it from Settings/Apps, I receive this exception:
AlreadyConfiguredException{message=Amplify has already been configured., cause=null, recoverySuggestion=Do not add plugins after calling `Amplify.configure()`.}

Your code
               AuthCategory().plugins.ifEmpty {
                    Amplify.addPlugin(AWSApiPlugin())
                    Amplify.addPlugin(AWSCognitoAuthPlugin())
                    Amplify.configure(applicationContext)
                }

**Which AWS service(s) are affected?**
auth- cognito

**Expected behavior**
I should be able to login/logout and re-login. The relogin portion is crashing.

**Screenshots**

My App simply crashes when I try to relaunch. The login of the second time crashes the app.

**Environment Information (please complete the following information):**
 I have the latest amazonaws libraries, as of today ( 3, Feb, 2022)
   implementation 'com.amazonaws:aws-android-sdk-auth-userpools:2.39.0'
    implementation 'com.amazonaws:aws-android-sdk-auth-ui:2.39.0'
    implementation 'com.amazonaws:aws-android-sdk-mobile-client:2.39.0'
    implementation 'com.amplifyframework:core:1.31.2'
    implementation 'com.amplifyframework:aws-api:1.31.2'
    implementation 'com.amplifyframework:aws-datastore:1.31.2'
    implementation 'com.amplifyframework:aws-auth-cognito:1.31.2'
    implementation 'com.amazonaws:aws-android-sdk-cognitoauth:2.39.0'

 - Device: [Simulator]
 - Android Version: version agnostic
 - Specific to simulators: No

**Additional context**
If the same issue has been addressed for Flutter ( https://github.com/aws-amplify/amplify-flutter/issues/412), can the fix be ported for Kotlin/Java ?

**Comment by tjleing** [comment] 2022-02-03 20:08
To clarify, by "close the app" do you mean force-closing (swiping up on the app)?

Also, where is your `Amplify.configure()` function?  I am unable to reproduce your issue when placing `Amplify.addPlugin(...); Amplify.configure()` in the `Application()` class and having a separate `Activity` that attempts to sign in, as is described in [the docs](https://docs.amplify.aws/lib/project-setup/create-application/q/platform/android/#4-initialize-amplify-in-the-application).  More detail on this front would help reproduce the issue.

**Comment by somardk** [comment] 2022-02-04 00:10
Here is how our code is constructed.

In Activity_1, which is the entry point of the app. Its onCreate() has these three lines to initialize

                 Amplify.addPlugin(AWSApiPlugin())
                Amplify.addPlugin(AWSCognitoAuthPlugin())
                Amplify.configure(applicationContext)

Then, it has a   login()  which calls:
               Amplify.Auth.signInWithWebUI (. )

In its successful callback, we load Activity2

In Activity_2, which has a logout() which calls
              Amplify.Auth.signOut( )

    In the success callback, Activity2 unloads itself, goes back to Activity1, somewhat like this:
             val intent= Intent(this, Activity1::class.java)
             startActivity(intent)

Logcat dumps this:
AlreadyConfiguredException{message=Amplify has already been configured., cause=null, recoverySuggestion=Do not add plugins after calling Amplify.configure().}

**Comment by somardk** [comment] 2022-02-04 00:25
The other scenario, "...by "close the app" do you mean force-closing..." goes like this:
From Activity1, we successfully transition to Activity2, then we go to Setting/App, double click our App's launch icon, which will attempt to invoke Activity1, the same occurs
"AlreadyConfiguredException{......"

**Comment by sktimalsina** [comment] 2022-02-04 02:46
@somardk It is not recommended to initialize Amplify in an activity as it can be created/destroyed several times during the lifecycle of the application. Rather, please move the configuration block to an instance of `Application` as described [here](https://docs.amplify.aws/lib/project-setup/create-application/q/platform/android/#4-initialize-amplify-in-the-application).

**Closed** 2022-02-11 15:06 UTC
Labels: bug, auth, closing soon
