### ISSUE TITLE
[DataStore] Issue with timeout exception

### ISSUE THREAD

**Issue by tomasfelder** [aws-amplify/amplify-android#585] opened 2020-06-17 19:20 UTC
Hi there,
I'm having an issue while using Amplify Datastore. I've upgraded my project to use Datastore because I was using the AppSync old way to communicate with the API. I needed DataStore because I need my app to work offline and then syncronize the data with the cloud. I followed all the steps to get it working but I cannot face why is it not working. My app crashes all time i run it with this expcetion. I'm using Kotlin language and Cognito Auth mode

`E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-3
    Process: com.example.scanningapp, PID: 2807
    java.lang.RuntimeException: java.util.concurrent.TimeoutException: The source did not signal an event for 5000 milliseconds and has been terminated.
        at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
        at io.reactivex.internal.observers.BlockingMultiObserver.blockingGetError(BlockingMultiObserver.java:153)
        at io.reactivex.Completable.blockingGet(Completable.java:1302)
        at com.amplifyframework.datastore.AWSDataStorePlugin.initialize(AWSDataStorePlugin.java:7)
        at com.amplifyframework.core.category.Category.initialize(Category.java:15)
        at com.amplifyframework.core.Amplify.lambda$beginInitialization$0(Amplify.java:1)
        at com.amplifyframework.core.-$$Lambda$Amplify$EB8h7rBH19uqUcPr0ZtYS0ww0r4.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
`
Thank you in advance!

**Comment by jamesonwilliams** [comment] 2020-06-17 20:07
Looks like a duplicate of #563

**Comment by tomasfelder** [comment] 2020-06-17 20:10
Yeah, sorry I've found that issue later. We can close it and continue on that thread

**Closed** 2020-06-17 23:52 UTC
