### ISSUE TITLE
SDK v1.17.8 | Private session option on AWS Amplify Social Login

### ISSUE THREAD

**Issue by Lavanya2204-developer** [aws-amplify/amplify-android#1368] opened 2021-06-08 07:32 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line
implementation 'com.amplifyframework:core:1.17.8'
implementation 'com.amplifyframework:aws-auth-cognito:1.17.8'

```

</details>

### Environment information

<details>

```
# Put output below this line
Welcome to Gradle 6.5!

Here are the highlights of this release:
 - Experimental file-system watching
 - Improved version ordering
 - New samples

For more details see https://docs.gradle.org/6.5/release-notes.html


------------------------------------------------------------
Gradle 6.5
------------------------------------------------------------

Build time:   2020-06-02 20:46:21 UTC
Revision:     a27f41e4ae5e8a41ab9b19f8dd6d86d7b384dad4

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.8 (AdoptOpenJDK 11.0.8+10)
OS:           Mac OS X 10.15.5 x86_64


```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/android

### Describe the bug

I am still facing the issue of getting automatically signed in to the same account after signing out for Social Login after upgrading to the latest SDK v1.17.8. 

However, when there are 2 accounts available for Gmail login it shows a screen where we are able to choose one of the accounts. But if there is only 1 account it seems to auto login.

Below are the changes that I've done as per the updated [documents:](https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/android)
1. Updated AndroidManifest.xml
2. Removed Response handler as it is not required for v1.17.8

cc @VishnuNCS

Previously closed Github ticket --> https://github.com/aws-amplify/amplify-android/issues/1287

**Comment by phanisaripalli** [comment] 2021-06-08 10:50
This issue has been worked on Mobile Client, [#524](https://github.com/aws-amplify/aws-sdk-android/issues/524) . As it is recommended to use Amplify for all the new development, could you please take it as a priority.

**Comment by raphkim** [comment] 2021-06-22 13:05
It has come to our attention that another way to resolve this would to make use of [`prompt` parameter](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) as specified by the OpenID specs, which is not supported by Amazon Cognito at the moment. We will discuss with the service team to consider the option of enabling this feature to force login prompts even without using custom tabs private session.

**Comment by richardmcclellan** [comment] 2021-07-08 20:02
This is a duplicate of https://github.com/aws-amplify/amplify-android/issues/1287.    Please follow that issue for further updates.

**Closed by richardmcclellan** 2021-07-08 20:02 UTC
Labels: auth, feature-request
