### ISSUE TITLE
update doesn't work on api(graphql)

### ISSUE THREAD

**Issue by azisoli** [aws-amplify/amplify-android#830] opened 2020-09-15 18:51 UTC
i'm using api(graphql) on a real project  and when i call Amplify.API.mutate(ModelMutation.update(profile)) it return response by previous data amounts and when i check database i don't see my changes. there is only on error in logs :
 W/AWSMobileClient: Could not check if ACCESS_NETWORK_STATE permission is available.
    java.lang.ClassNotFoundException: android.support.v4.content.ContextCompat

can this error be the case of my problem or it can be other problem ?
thanks

**Comment by jamesonwilliams** [comment] 2020-09-15 20:54
Duplicate of https://github.com/aws-amplify/amplify-android/issues/827

TLDR, please try 1.3.2 of Amplify Android which was just released.

**Closed by jamesonwilliams** 2020-09-15 20:54 UTC
