### ISSUE TITLE
QueryPredicate API - Possible BUG - Amplify 1.0

### ISSUE THREAD

**Issue by KayIlory** [aws-amplify/amplify-android#561] opened 2020-06-05 18:04 UTC
The Query Predicate only currently seems to work for String equals and contains. All other data types such as float are not working with the API. It returns a zero result for all request with this datatype. Even with eq, lt, gt, le, ge etc. Running this return no results even though dynamo has 25 records that meet the set criteria.

Assume a GraphQL with datatype longitude and latitude of type Float.

```java
public void getHealthCentresByConsultantFirstPage(final Float longitudeStart,
        final Float longitudeEnd,
        final Float latitudeStart,
        final Float latitudeEnd) {
    QueryPredicateGroup predicate = HealthCentreConsultant.LONGITUDE.ge(longitudeStart)
        .and(HealthCentreConsultant.LONGITUDE.le(longitudeEnd))
        .and(HealthCentreConsultant.LATITUDE.ge(latitudeStart))
        .and(HealthCentreConsultant.LATITUDE.le(latitudeEnd));

    getHealthCentresByConsultant(ModelQuery.list(HealthCentreConsultant.class, predicate, ModelPagination.firstPage()));
}

public void getHealthCentresByConsultant(GraphQLRequest<PaginatedResult> request) {
    new Thread(() -> Amplify.API.query(request, response -> {
        if (response.hasData()) {
            for (HealthCentreConsultant healthCentreConsultant : response.getData().getItems()) {
                Timber.d(healthCentreConsultant.toString());
            }
            if (response.getData().hasNextResult()) {
                GraphQLRequest<PaginatedResult> healthCentreConsultantNextPaginatedResult = 
                        response.getData().getRequestForNextResult();
            }
        }
    }, error -> {
        Timber.e(error.getCause());
    })).start();
}
```

**Comment by richardmcclellan** [comment] 2020-06-05 18:17
hey @KayIlory, can you try changing `GraphQLRequest<PaginatedResult>` to `GraphQLRequest<PaginatedResult<HealthCentreConsultant>` in the `getHealthCentresByConsultant ` method signature and see if that helps?

**Comment by richardmcclellan** [comment] 2020-06-05 18:43
Also, try replacing `QueryPredicateGroup` with `QueryPredicateGroup<Float>`.

**Comment by KayIlory** [comment] 2020-06-05 18:50
Unfortunately doesnt help..

    public void getHealthCentresByConsultantFirstPage(final float longitudeStart,
                                                      final float longitudeEnd,
                                                      final float latitudeStart,
                                                      final float latitudeEnd
                                                      ) {
        QueryPredicateGroup predicate = HealthCentreConsultant.LONGITUDE.ge(longitudeStart)
                .and(HealthCentreConsultant.LONGITUDE.le(longitudeEnd))
                .and(HealthCentreConsultant.LATITUDE.ge(latitudeStart))
                .and(HealthCentreConsultant.LATITUDE.le(latitudeEnd));

        getHealthCentresByConsultant(ModelQuery.list(HealthCentreConsultant.class, predicate,
                ModelPagination.firstPage()));
    }

    public void getHealthCentresByConsultant(GraphQLRequest<PaginatedResult<HealthCentreConsultant>> request) {
        new Thread(() -> Amplify.API.query(request, response -> {
            if (response.hasData()) {
                for (HealthCentreConsultant healthCentreConsultant : response.getData().getItems()) {
                    Timber.d(healthCentreConsultant.toString());
                }
                if (response.getData().hasNextResult()) {
                    GraphQLRequest<PaginatedResult<HealthCentreConsultant>> healthCentreConsultantNextPaginatedResult = response.getData().getRequestForNextResult();
                }
            }
        }, error -> {
            //Timber.e(healthCentresActivity.getTag(), "Query Failure", error);
        })).start();
    }

**Comment by KayIlory** [comment] 2020-06-05 22:06
> Also, try replacing `QueryPredicateGroup` with `QueryPredicateGroup<Float>`.

I don't think that is possible. Android throws a compilation error when I try that. For sure no data gets returned but when I use another data point of type string I get results for that string. It just doesnt work with any other data types apart from String I have experienced so far

**Comment by richardmcclellan** [comment] 2020-06-11 05:05
Hey Kayllory, I built a quick sample app with similar to yours, and am not able to reproduce.  Here's what I did:

schema.graphql:
```
type Place @model {
  id: ID!
  name: String!
  longitude: Float!
  latitude: Float!
}
```

Create some Place objects:
```
    public void createPlaces() {
        List<Place> places = Arrays.asList(
            Place.builder().name("Starbucks Market Street San Francisco CA").longitude(-122.407694f).latitude(37.784324f).build(),
            Place.builder().name("Starbucks Sloat Blvd San Francisco CA").longitude(-122.4904542f).latitude(37.73394698f).build(),
            Place.builder().name("Starbucks 5th Avenue Anchorage AK").longitude(-149.8935557f).latitude(61.21759217f).build(),
            Place.builder().name("Starbucks Northern Lights Anchorage AK").longitude(-149.9054948f).latitude(61.19533942f).build()
        );

        for(Place place : places) {
            Amplify.API.mutate(ModelMutation.create(place), response -> {
                Log.d(TAG, "created a Place");
            }, error -> {
                Log.d(TAG, "error: " + error);
            });
        }
    }
```

List the places with a predicate to filter around Alaska:
```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        listPlaces(-170f, -130.9f, 60f, 80f);
    }

    public void listPlaces(final Float longitudeStart,
                           final Float longitudeEnd,
                           final Float latitudeStart,
                           final Float latitudeEnd) {
        QueryPredicate predicate = Place.LONGITUDE.ge(longitudeStart)
                .and(Place.LONGITUDE.le(longitudeEnd))
                .and(Place.LATITUDE.ge(latitudeStart)
                .and(Place.LATITUDE.le(latitudeEnd)));
        Amplify.API.query(ModelQuery.list(Place.class, predicate, ModelPagination.firstPage()), response -> {
            if(response.hasData()) {
                for(Place place : response.getData().getItems()) {
                    Log.d(TAG, "place:  " + place);
                }
            }
        }, error -> {
            Log.d(TAG, "error:  " + error);
        });
    }
```

From this query, the two Places in Alaska are returned, as expected.

My best guess is that your `QueryPredicate` is being applied after `limit` (which defaults to 1000), and none of the first 1000 results meet your criteria.    You could confirm this by fetching all result pages and/or increasing the page `limit` (`ModelPagination.firstPage().limit(10000)`).  You could solve this using the approach described here: https://github.com/aws-amplify/amplify-cli/issues/1915#issuecomment-515777524

**Comment by KayIlory** [comment] 2020-06-11 09:19
Hi @richardmcclellan,
Will test this all day today to get to the bottom of it. I have only 500 records in the table and not using limit with the error reported. I also tried with eq to as well. WIll revert in next 24hrs 

> Hey Kayllory, I built a quick sample app with similar to yours, and am not able to reproduce. Here's what I did:
> 
> schema.graphql:
> 
> ```
> type Place @model {
>   id: ID!
>   name: String!
>   longitude: Float!
>   latitude: Float!
> }
> ```
> 
> Create some Place objects:
> 
> ```
>     public void createPlaces() {
>         List<Place> places = Arrays.asList(
>             Place.builder().name("Starbucks Market Street San Francisco CA").longitude(-122.407694f).latitude(37.784324f).build(),
>             Place.builder().name("Starbucks Sloat Blvd San Francisco CA").longitude(-122.4904542f).latitude(37.73394698f).build(),
>             Place.builder().name("Starbucks 5th Avenue Anchorage AK").longitude(-149.8935557f).latitude(61.21759217f).build(),
>             Place.builder().name("Starbucks Northern Lights Anchorage AK").longitude(-149.9054948f).latitude(61.19533942f).build()
>         );
> 
>         for(Place place : places) {
>             Amplify.API.mutate(ModelMutation.create(place), response -> {
>                 Log.d(TAG, "created a Place");
>             }, error -> {
>                 Log.d(TAG, "error: " + error);
>             });
>         }
>     }
> ```
> 
> List the places with a predicate to filter around Alaska:
> 
> ```
>     @Override
>     protected void onCreate(Bundle savedInstanceState) {
>         super.onCreate(savedInstanceState);
>         listPlaces(-170f, -130.9f, 60f, 80f);
>     }
> 
>     public void listPlaces(final Float longitudeStart,
>                            final Float longitudeEnd,
>                            final Float latitudeStart,
>                            final Float latitudeEnd) {
>         QueryPredicate predicate = Place.LONGITUDE.ge(longitudeStart)
>                 .and(Place.LONGITUDE.le(longitudeEnd))
>                 .and(Place.LATITUDE.ge(latitudeStart)
>                 .and(Place.LATITUDE.le(latitudeEnd)));
>         Amplify.API.query(ModelQuery.list(Place.class, predicate, ModelPagination.firstPage()), response -> {
>             if(response.hasData()) {
>                 for(Place place : response.getData().getItems()) {
>                     Log.d(TAG, "place:  " + place);
>                 }
>             }
>         }, error -> {
>             Log.d(TAG, "error:  " + error);
>         });
>     }
> ```
> 
> From this query, the two Places in Alaska are returned, as expected.
> 
> My best guess is that your `QueryPredicate` is being applied after `limit` (which defaults to 1000), and none of the first 1000 results meet your criteria. You could confirm this by fetching all result pages and/or increasing the page `limit` (`ModelPagination.firstPage().limit(10000)`). You could solve this using the approach described here: [aws-amplify/amplify-cli#1915 (comment)](https://github.com/aws-amplify/amplify-cli/issues/1915#issuecomment-515777524)

I will test on this all day today. I have only 600 records in the table and not using and limit restrictions.

**Comment by KayIlory** [comment] 2020-06-11 12:04
[issue.zip](https://github.com/aws-amplify/amplify-android/files/4764585/issue.zip)

@richardmcclellan - so it still doesnt work and below is reasons why. I followed the exact same process as you. The only difference is that I insert the BULK data using boto3 and i included the python code for that and the file to see if you can replicate the issue.


Here is a sample attached in the link. Also to note we had this working under the SDK

**Comment by richardmcclellan** [comment] 2020-06-15 20:58
From @kayllory on Discord: 

> I think I am getting to the bottom of the issue with the filter.  Filtering works if data is inserted to dynamo via the amplify route. If data is loaded via boto3 direct to dynamo, this causes some of the issues I am seeing.. this path worked well with the SDK but it seems might not be suitable. What happens to existing loaded data

Closing, as predicates are working as expected.

**Closed by richardmcclellan** 2020-06-15 20:58 UTC
Labels: API, Bug, Clarification Needed, Closing Soon
