### ISSUE TITLE
Allow API endpoint to be configured via AWSApiPlugin

### ISSUE THREAD

**Issue by cherrydev** [aws-amplify/amplify-android#1879] opened 2022-08-09 17:53 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Not applicable

### Amplify Categories

REST API, GraphQL API

### Gradle script dependencies

N/A

### Environment information

N/A

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/graphqlapi/existing-resources/q/platform/android/

### Describe the feature request

API endpoints should be configurable using the plugin configuration builder mechanism to support custom domains. Because of limitations to the Amplify CLI tools and design, there are a number of modifications to an Amplify app that require deleting and-recreating an API (such as making changes to Auth category that is used by the API) and each time you do that, you end up with a different API ID (which cannot be overridden) which changes the API endpoint URL. Without custom domains, this would require modifying, re-building and re-deploying any applications that use the API.

Right now the only place where the endpoint URL can be modified is in the `amplifyconfiguration.json` file, which is a generated file. While it can be edited, it will be overwritten every time `amplify pull` is called which makes maintaining changes awkward and error-prone. My suggestion is that a new method be added to `AWSApiPlugin.Builder` with the signature: `configureEndpoint(String forApiName, String endpointUrl) AWSApiPlugin.Builder`. This will pass the endpoint URL configuration down into the construction of the `AWSApiPlugin` object.

### Code Snippet

```kotlin
// Put your code below this line.
Amplify.addPlugin(
  AWSApiPlugin.builder().configureEndpoint("myapiname", "http://my-custom-domain.domain.example/graphql")
    .build()
)
```

**Comment by abdallahshaban557** [comment] 2022-10-25 23:15
Closing this as a duplicate of https://github.com/aws-amplify/amplify-android/issues/1879

**Closed by abdallahshaban557** 2022-10-25 23:15 UTC
Labels: feature-request, GraphQL API, p4, REST API, api, feature-parity
