### ISSUE TITLE
Amplify.Auth.fetchAuthSession() returns isSignedIn value false even though refresh token hasn't expired in Samsung Galaxy A53 

### ISSUE THREAD

**Issue by bijaykumarpun** [aws-amplify/amplify-android#2725] opened 2024-03-06 06:31 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin - Coroutines

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line
    implementation 'com.amplifyframework:core:2.13.0'
    implementation 'com.amplifyframework:aws-auth-cognito:2.13.0'
    implementation 'com.amplifyframework:core-kotlin:2.13.0'


```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 8.0
------------------------------------------------------------

Build time:   2023-02-13 13:15:21 UTC
Revision:     62ab9b7c7f884426cf79fbedcf07658b2dbe9e97

Kotlin:       1.8.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.6 (Oracle Corporation 17.0.6+9-LTS-190)
OS:           Mac OS X 14.1.1 aarch64



```

</details>

### Describe the bug

This is a very device-specific issue and reported on Samsung Galaxy A53 SM-A536E only.

- User successfully signs in with their username and password
- Restarting the app works as usual, they are authenticated (`AWSCognitoAuthSession.isSignedIn` value is `true`
- They open the app after some time (Probably after the session token expired)
- `AWSCognitoAuthSession.isSignedIn` value is `false` and  access token is not refreshed

Because the access token is not refreshed, they are navigated to the sign in screen (this is our own logic).

I want to know if there is anything that could potentially prevent the session token from being refreshed. As this issue has occurred in only one device, and debugging isn't going to be easy/accessible, I'm trying to see if there is anything that I missed on my end and how I can solve this issue.

I want to emphasize again that this only occurs on one device only (as far as the reports go), and I haven't been able to reproduce on any other deivces.

### Code Snippet

```kotlin
 val session = Amplify.Auth.fetchAuthSession() as AWSCognitoAuthSession

 if (session.isSignedIn) {

    // Proceed with the session token

    } else {

     // Navigate to sign in screen
}
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### amplifyconfiguration.json

```
{
    "UserAgent": "aws-amplify-cli/0.1.0",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "ap-southeast-****redacted****",
            "AppClientId": "****redacted****",
            "Region": "ap-southeast-2"
        }
    },
    "Auth": {
        "Default": {
            "OAuth": {
                "WebDomain": "****redacted****",
                "AppClientId": "****redacted****",
                "SignInRedirectURI": "myapp://callback/",
                "SignOutRedirectURI": "myapp://signout/",
                "Scopes": [
                    "aws.cognito.signin.user.admin",
                    "email",
                    "openid",
                    "phone",
                    "profile"
                ]
            },
            "authenticationFlowType": "USER_SRP_AUTH",
            "socialProviders": [],
            "usernameAttributes": [
                "EMAIL"
            ],
            "signupAttributes": [
                "EMAIL"
            ],
            "passwordProtectionSettings": {
                "passwordPolicyMinLength": 8,
                "passwordPolicyCharacters": [
                    "REQUIRES_LOWERCASE",
                    "REQUIRES_UPPERCASE",
                    "REQUIRES_NUMBERS",
                    "REQUIRES_SYMBOLS"
                ]
            },
            "mfaConfiguration": "OPTIONAL",
            "mfaTypes": [
                "TOTP"
            ],
            "verificationMechanisms": [
                "EMAIL"
            ]
        }
    }
}
```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by tylerjroach** [comment] 2024-03-06 17:09
`isSignedIn` only reports false when the stored credential type is `AmplifyCredential.IdentityPool`, or an error has occurred.

```
AWSCognitoAuthSession(
    false, //isLoggedIn
    identityIdResult = AuthSessionResult.failure(exception),
    awsCredentialsResult = AuthSessionResult.failure(exception),
    userSubResult = AuthSessionResult.failure(exception),
    userPoolTokensResult = AuthSessionResult.failure(exception)
)
```

It would be helpful to try and log the exception which is provided in each of the result types inside the auth session. Without more information into the issue (especially if you are only seeing this on a single device type), its difficult to determine what may be happening.

**Comment by mattcreaser** [comment] 2024-03-19 15:41
Marking this as a bug pending further investigation.

@bijaykumarpun would you be able to take @tylerjroach's suggestion and add log messages indicating what errors, if any, are returned in the various results in `AWSCognitoAuthSession`?

**Comment by tylerjroach** [comment] 2024-03-21 21:01
DST should not cause an issue unless the user is in a region that recently added or removed DST and their Operating System has not updated to be aware that the region is participating (or not) in DST).

It's possible that a library has added the internet permission for you and merged that permission into the manifest but it is best to add permissions on your own app manifest.

However, if the users phone does not have internet, this would be the cause reason for the failures as seen.

**Comment by vincetran** [comment] 2024-04-23 23:22
Hi @bijaykumarpun, I just happened to run into this issue and noticed its similarity to a different issue (#2783). Essentially if the user is offline and the access token has expired, `isSignedIn` returns false even though the refresh token may still be valid. Can you verify if the trouble device was attempting to (re)launch the app after your configured active token expiration?

**Comment by Mohammad-amleh** [comment] 2024-05-22 14:59
this case face me also

**Comment by tylerjroach** [comment] 2024-08-07 19:40
I believe this issue was fixed in the referenced by https://github.com/aws-amplify/amplify-android/pull/2830

**Closed by tylerjroach** 2024-08-07 19:40 UTC
Labels: bug, auth
