### ISSUE TITLE
Android Amplify Signout issue

### ISSUE THREAD

**Issue by ten-skv** [aws-amplify/amplify-android#2218] opened 2023-01-05 17:55 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line
implementation "com.amplifyframework:core:1.37.9"
implementation 'com.amplifyframework:aws-auth-cognito:1.37.9'

```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 6.1.1
------------------------------------------------------------

Build time:   2020-01-24 22:30:24 UTC
Revision:     a8c3750babb99d1894378073499d6716a1a1fa5d

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          13 (Oracle Corporation 13+33)
OS:           Mac OS X 10.16 x86_64


```

</details>

### Describe the bug

We are using both "Amplify.Auth.signInWithSocialWebUI" (some users using sso)  and "Amplify.Auth.signIn" (some users using our user/password).

**Issue:** Even-though initially user logged in using  "Amplify.Auth.signIn" , when signing out, user is taken to the browser to  and it throws error.
AuthException{message=Failed to sign out, cause=com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthServiceException: Timed out while waiting for sign-out redirect response., recoverySuggestion=See attached exception for more details}
        at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$22.onError(AWSCognitoAuthPlugin.java:1198)
.....

At this scenario, when user trying to re-login ("Amplify.Auth.signIn") with user_name/password, it accepts any password and user was able to successfully login.

### Reproduction steps (if applicable)

**To Reproduce**
1. Login with user name/password using Amplify.Auth.signIn.
2. You will be successfully signed in and get session token.
3. Logout from that user using Amplify.Auth.signOut(), it throws timeout eceptions.
4. Try to relogin with user name/password using Amplify.Auth.signIn.
5. It  accepts any password.

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### amplifyconfiguration.json

Amplify configuration:
```
{
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "UserAgent": "aws-amplify-cli/0.1.0",
        "Version": "0.1.0",
        "IdentityManager": {
          "Default": {}
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "us-east-2_xxxxxxxxxx",
            "AppClientId": "xxxxxxp90rhg4hxxxxxxxxx",
            "Region": "us-east-2"
          }
        },
        "Auth": {
          "Default": {
            "OAuth": {
              "WebDomain": "xxxxxxx.auth.us-east-1.amazoncognito.com",
              "AppClientId": "xxxxxxxxxrhg4h9xxxxxxxx",
              "SignInRedirectURI": "xxxxx://signin",
              "SignOutRedirectURI": "xxxxx://signout",
              "responseType": "code",
              "Scopes": [
                "phone",
                "email",
                "openid",
                "profile",
                "aws.cognito.signin.user.admin"
              ]
            },
            "authenticationFlowType": "USER_SRP_AUTH"
          }
        }
      }
    }
  }
}
```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by ten-skv** [comment] 2023-01-05 19:20
FYI: I already gone through this thread: https://github.com/aws-amplify/amplify-android/issues/1990
We will not be able to upgrade to v2 at this moment.

**Comment by gpanshu** [comment] 2023-01-05 19:31
Hi @ten-skv from what I understand in your issue is that after you login using SRP when you sign out it takes you to the browser and you get the timeout exception. Is that correct?

**Comment by tylerjroach** [comment] 2023-01-05 19:33
@ten-skv Unfortunately, v1 does not handle mixed sign in (webui + srp) as well as v2 does. The v1 implementation will trigger the CustomTab launch if there is an "Oauth" block in your configuration file, indicating that web sign in is configured. 

The expectation is that if a user did not sign in via web, the redirect should be triggered immediately back to the application and the rest of the sign in proceeds.

Are you able to easily reproduce this, and are you observing on all browsers?

FYI, v1 also has some differences in behavior on calling signIn while already signedIn. In this case, the signOut is failing and throwing the error. This means that the current user remained logged in. The reason it appears that it is accepting any password is because it is returning the current signed in user, it's not actually accepting any typed password.

**Comment by ten-skv** [comment] 2023-01-05 19:46
We are using both "Amplify.Auth.signInWithSocialWebUI" (some users using sso) and "Amplify.Auth.signIn" (some users using our user/password).

In this scenario, I'm signing in using "Amplify.Auth.signIn" (username and password). And when I call "Amplify.Auth.signOut" it takes to an external browser and redirects back to the app. I assume it is chrome browser. At this time it throws the time out exception. Some times it's successfully signout and able to relogin (it validates the username/password)

Amplify.Auth.signOut(
                    {
                        Timber.i { "Profile - F: Successfully Signedout from Cognito!" }                      
                    },
                    {
                        Timber.e(it)
                        showOfflineMessage("Signout unsuccessful!")
                       // It goes here
                    })

**Comment by nazarcybulskij** [comment] 2023-01-23 12:27
@ten-skv When I updated the **AndroidManifest.xml**  by adding additional intent-filters, the logout started working fine

```
 <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="myapp"/>
                <data android:host="callback"/>
            </intent-filter>

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="myapp"/>
                <data android:host="signout"/>
            </intent-filter>
```

**Comment by ten-skv** [comment] 2023-01-23 13:34
@nazarcybulskij  Is it on 1.17.9 version? I tried and it's not working for me. Here is my manifest snippet.

......
		<activity
            android:name="com.amplifyframework.auth.cognito.activities.HostedUIRedirectActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="myapp" />
                <data android:host="callback"/>
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="myapp" />
                <data android:host="signout"/>
            </intent-filter>
        </activity>
.....

**Comment by nazarcybulskij** [comment] 2023-01-23 14:04
@ten-skv  add intent-filters in MainActivity, not  HostedUIRedirectActivity

**Comment by ten-skv** [comment] 2023-01-23 14:20
@nazarcybulskij  I just tried with the added intent and still I'm able to login with the same user with invalid password (The session is still active).

**Comment by tylerjroach** [comment] 2023-01-23 15:00
The correct implementation is to add the intent filters to the HostedUIRedirectActivity.

However, please make sure your scheme's and host's are correct in the manifest and exactly match what you have configured. Instead of "myapp", please make sure your host matches whatever you have masked as "xxxxx" in your configuration. 

```
SignInRedirectURI": "xxxxx://signin",
"SignOutRedirectURI": "xxxxx://signout",
```

Unless you are trying to add custom behavior to the sign in and sign out flows, you don't necessarily have to provide both a sign in and sign out intent, instead using one that captures both (removing the "hosts"). See here: https://docs.amplify.aws/lib-v1/auth/social/q/platform/android/#update-androidmanifestxml

```
  <activity
      android:name="com.amplifyframework.auth.cognito.activities.HostedUIRedirectActivity"
      android:exported="true">
      <intent-filter>
          <action android:name="android.intent.action.VIEW" />
          <category android:name="android.intent.category.DEFAULT" />
          <category android:name="android.intent.category.BROWSABLE" />
          <data android:scheme="myapp" />
      </intent-filter>
  </activity>
```

**Comment by ten-skv** [comment] 2023-01-23 15:44
@tylerjroach  I'm using the exact scheme which I have configured (I never changed it from previous implementation). Signout not working after I upgrade to v1.37.9. Previously I was using v1.4.1 which was working fine (I have used a different activity configured in Androidmanifest.xml - "com.amazonaws.mobileconnectors.cognitoauth.activities.CustomTabsRedirectActivity")

It is pretty easy to reproduce and it's happening every time. Again I'm using mix of both logins "Amplify.Auth.signInWithSocialWebUI" and "Amplify.Auth.signIn".

**Comment by tylerjroach** [comment] 2023-01-23 15:49
@ten-skv Have you removed `CustomTabsRedirectActivity`? from your manifest? If you can, please post any relevant snippets from your current manifest to help us diagnose where the problem may be.

**Comment by ten-skv** [comment] 2023-01-23 15:53
@tylerjroach  Yes I have removed the CustomTabsRedirectActivity. Here is my current manifest.

<application
        android:allowBackup="false"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="false"
        tools:replace="android:supportsRtl, android:allowBackup"
        android:name="com.tenna.android.tfa.tfaapp.App"
        android:hardwareAccelerated="true"
        android:largeHeap="true"
        android:requestLegacyExternalStorage="true"
        android:theme="@style/AppTheme">
        <uses-library android:name="org.apache.http.legacy" android:required="false" />
        <meta-data
            android:name="com.google.android.actions"
            android:resource="@xml/actions" />
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/tenna_logo" />
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_color"
            android:resource="@color/colorAccent" />
        <meta-data
            android:name="com.google.android.gms.vision.DEPENDENCIES"
            android:value="ocr" />
        <meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="@string/google_cloud_api_map"/>
        <meta-data
            android:name="firebase_crashlytics_collection_enabled"
            android:value="${crashlyticsCollectionEnabled}"/>
        <provider
            android:authorities="com.tenna.android.tfa.tfaapp.fileprovider"
            android:name="androidx.core.content.FileProvider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths" />
        </provider>
        <activity
            android:name="com.tenna.android.tfa.tfaapp.MainActivity"
            android:screenOrientation="portrait"
            android:label="@string/app_name"
            android:launchMode="singleInstance"
            android:exported="true"
            android:theme="@style/AppTheme.NoActionBar">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <nav-graph android:value="@navigation/nav_main" />
            <intent-filter>
                <action android:name="android.intent.action.SEARCH" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data
                    android:host="android.xxxxx.com"
                    android:scheme="https" />
            </intent-filter>
        </activity>


        <activity
            android:name="com.amplifyframework.auth.cognito.activities.HostedUIRedirectActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="xxxx" />
            </intent-filter>
        </activity>

        <receiver
            android:name="com.tenna.android.tfa.tfaapp.receiver.InternetStateReceiver"
            android:label="NetworkStateReceiver"
            android:exported="false">
            <intent-filter>
                <action android:name="android.net.conn.CONNECTIVITY_CHANGE" />
                <action android:name="android.net.wifi.WIFI_STATE_CHANGED" />
            </intent-filter>
        </receiver>
        <service android:name=".service.fcm.TennaFcmService"
            android:exported="true">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        <service android:name="org.altbeacon.beacon.service.BeaconService" tools:node="replace">
            <meta-data android:name="longScanForcingEnabled" android:value="true"/>
        </service>

        <service
            android:name="com.helpscout.beacon.internal.push.BeaconFirebaseMessagingService"
            android:stopWithTask="false"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>

        <activity
            android:name="androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity"
            android:exported="false" />
        <activity
            android:name="androidx.test.core.app.InstrumentationActivityInvoker$EmptyActivity"
            android:exported="false" />
        <activity
            android:name="androidx.test.core.app.InstrumentationActivityInvoker$EmptyFloatingActivity"
            android:exported="false" />

    </application>

**Comment by tylerjroach** [comment] 2023-01-23 17:08
Do you still have `override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?)` in your activity that calls signOut? If so, could you paste that block here?

**Comment by tylerjroach** [comment] 2023-01-23 17:27
One additional question @ten-skv, if you sign in with `signInWithSocialWebUI` do you see the same issue on signOut, or is it only if you start from an SRP flow?

**Comment by ten-skv** [comment] 2023-01-23 17:39
For "signInWithSocialWebUI" flow "signout" works fine.

I have this code on ActivityResults. It executes only for "signInWithSocialWebUI" (signin).


`override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)

        if (requestCode == AWSCognitoAuthPlugin.WEB_UI_SIGN_IN_ACTIVITY_CODE) {
            Amplify.Auth.handleWebUISignInResponse(data)
        }
    }`

**Comment by tylerjroach** [comment] 2023-01-23 18:15
@ten-skv Can you try removing that line? HostedUIRedirectActivity handles the web sign in/out on its own, and does not require that block. It's possible that this is interfering.

If this still doesn't resolve the issue, I'd love to chat more on https://discord.gg/amplify and possibly set up a call.

**Comment by ten-skv** [comment] 2023-01-24 15:11
@tylerjroach HostedUIRedirectActivity handles code is executed only when social signin flow happens. But I removed it and tried and still same issue.

**Comment by tylerjroach** [comment] 2023-01-24 16:10
Hi @ten-skv, unfortunately on v1, the Auth library does not track whether a sign in is from SRP or a social web sign in. This is the reason that the custom tab opens on signout, regrardless of the sign in method used. It is still critical that this HostedUIRedirectActivity receives the redirect on the signout of an SRP sigin. I would love to work with you 1-1 to further investigate this issue if you are willing. Please reach out on Discord and we can set up a call.

**Comment by ten-skv** [comment] 2023-01-24 16:11
@tylerjroach  Thank you for helping me out. Sure will reach out in Discord.

**Comment by tylerjroach** [comment] 2023-01-31 22:06
I have a PR fix for a different sign out issue (Hosted UI Custom Tab getting stuck on signout, especially Firefox). Would be curious if this has any impact to the issue you are running into. https://github.com/aws-amplify/aws-sdk-android/pull/3184

**Comment by tylerjroach** [comment] 2023-03-10 19:58
Hi @ten-skv Checking to see if you have been able to diagnose this issue any further after our sync.

**Comment by tylerjroach** [comment] 2023-04-06 17:25
I'm going to go ahead and close this issue, but please reach out if you continue to see the sign out issue described.

**Closed by tylerjroach** 2023-04-06 17:25 UTC
Labels: bug, pending-response, auth, closing soon

**Comment by tylerjroach** [comment] 2023-07-26 13:27
Hi @aligkts,

Can you please open a new issue with your implementation details and exactly what issues you are seeing.
Please also include the version of Amplify being used.

You can also reach out on our Discord server through https://discord.gg/amplify
