### ISSUE TITLE
graphql document string with tab indent (not space) causes client error

### ISSUE THREAD

**Issue by ragingsquirrel3** [aws-amplify/amplify-android#1596] opened 2021-12-03 17:22 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

GraphQL API

### Gradle script dependencies

<details>

```groovy
// Put output below this line
implementation "com.amplifyframework:aws-api:1.28.3-rc"
implementation "com.amplifyframework:aws-api-appsync:1.28.3-rc"

```

</details>

### Environment information

<details>

```
# Put output below this line
Gradle 6.1.1
------------------------------------------------------------

Build time:   2020-01-24 22:30:24 UTC
Revision:     a8c3750babb99d1894378073499d6716a1a1fa5d

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_231 (Oracle Corporation 25.231-b11)
OS:           Mac OS X 10.15.7 x86_64

```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/android/

### Describe the bug

When making a graphql API request with a custom string, client is throwing error when the string is indented with tabs.

A graphql document string like
```
'query MyQuery {
      listBlogs {
      \titems {
          id
          name
          createdAt
        }
      }
    }'
```

notice the tab on 3rd line, causes this error:
`NonRetryableException{message=OkHttp client request failed., cause=null, recoverySuggestion=Irrecoverable error}
E/amplify:flutter:api(22539): 	at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:147)
E/amplify:flutter:api(22539): 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
E/amplify:flutter:api(22539): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/amplify:flutter:api(22539): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/amplify:flutter:api(22539): 	at java.lang.Thread.run(Thread.java:923)
`

Note this is reprod when using from amplify-flutter library in android environment, but root cause has been traced here. amplify-ios does not have this issue and error goes away when tabs removed (or replaced with spaces). amplify-flutter can implement a workaround to strip the whitespace before sending over, but thought android users might face this issue, as well. It's pretty hard to debug when it happens.

Expectation: non-significant whitespace indented with tabs should not cause a client error like this.

### Reproduction steps (if applicable)

see above

### Code Snippet

```kotlin
// Put your code below this line.
operation = Amplify.API.query(
                    SimpleGraphQLRequest<String>(
                        document,
                        variables,
                        String::class.java,
                        GsonVariablesSerializer()
                    ),
                    responseCallback,
                    errorCallback
                )
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by chrisbonifacio** [comment] 2022-09-21 18:09
Closing as a duplicate of https://github.com/aws-amplify/amplify-flutter/issues/1175

**Closed** 2022-09-21 18:11 UTC
Labels: improvement, datastore, pending-triage
