### ISSUE TITLE
[Authenticator] The library should declare the needed consumer proguard rules

### ISSUE THREAD

**Issue by pmellaaho** [aws-amplify/amplify-android#2797] opened 2024-04-29 04:48 UTC
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui-android/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui-android/blob/main/CONTRIBUTING.md#reporting-bugsfeature-requests).

### Which UI component?

Authenticator

### Gradle script dependencies

```groovy
// Put output below this line
authenticatorVersion = "1.1.0"
```

### Environment information

```
# Put output below this line
Gradle 8.5

```

### Describe the bug

When I'm doing a release build of my App that uses Amplify UI I get the following:

`> Task :app:minifyReleaseWithR8
AGPBI: {"kind":"warning","text":"Missing class kotlinx.parcelize.Parcelize (referenced from: com.amplifyframework.notifications.pushnotifications.NotificationContentProvider$FCM and 2 other contexts)","sources":[{}],"tool":"R8"}`

I can get around this by including the following in my proguardrules.pro
`-dontwarn kotlinx.parcelize.Parcelize*`

But the needed rules should really come with the library

### Code Snippet

```java
// Put your code below this line.

```

### Log output

```
// Put your logs below this line
AGPBI: {"kind":"warning","text":"Missing class kotlinx.parcelize.Parcelize (referenced from: com.amplifyframework.notifications.pushnotifications.NotificationContentProvider$FCM and 2 other contexts)","sources":[{}],"tool":"R8"}

```

**Comment by vincetran** [comment] 2024-05-21 22:08
Hi @pmellaaho, I've looked at this report and have been unable to reproduce this issue. In my sample app, I have the following Amplify dependencies:

```
    val amplify = "2.17.0"
    implementation("com.amplifyframework:core:$amplify")
    implementation("com.amplifyframework:aws-api:$amplify")
    implementation("com.amplifyframework:aws-datastore:$amplify")
    implementation("com.amplifyframework:aws-auth-cognito:$amplify")
    implementation("com.amplifyframework:aws-push-notifications-pinpoint:$amplify")
```

I have minify enabled and have the default empty proguard rules:

```
debug {
    isMinifyEnabled = true
    proguardFiles(
        getDefaultProguardFile("proguard-android-optimize.txt"),
        "proguard-rules.pro"
    )
}
```

Yet I'm able to build and minify without issue. Can you provide any more details that would suggest the library is at fault?

**Comment by pmellaaho** [comment] 2024-05-22 06:58
Hello, thanks for looking into this.
I have the following dependencies:

`authenticator = { module = "com.amplifyframework.ui:authenticator", version.ref = "authenticatorVersion" }
aws-auth-cognito = { module = "com.amplifyframework:aws-auth-cognito", version.ref = "awsAuthCognitoVersion" }
core-kotlin = { module = "com.amplifyframework:core-kotlin", version.ref = "coreKotlinVersion" }`

I'm not sure which changes in my code has made the build warning to go away but I'm not seeing it anymore either. I have to return to this subject if the problem appears later again.

**Comment by vincetran** [comment] 2024-05-23 19:23
Gotcha, thanks for following up then! I'll close this issue and if the problem comes up again, please let us know.

**Closed by vincetran** 2024-05-23 19:23 UTC
Labels: bug, auth
