### ISSUE TITLE
CognitoUserSession is not valid because idToken is null

### ISSUE THREAD

**Issue by alfdan2000** [aws-amplify/amplify-android#1862] opened 2022-07-28 17:40 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line

dependencies {

    //Amplify core dependency
    implementation 'com.amplifyframework:core:1.36.2'
    implementation 'com.amplifyframework:aws-auth-cognito:1.36.2'
    implementation 'com.amplifyframework:aws-api:1.36.2'

    //Cognito dependencies
    implementation 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.6.29'
    implementation 'com.amazonaws:aws-android-sdk-core:2.6.29'
    implementation 'androidx.navigation:navigation-fragment:2.2.2'
    implementation 'androidx.navigation:navigation-ui:2.2.2'
    implementation 'com.amplifyframework:aws-datastore:1.36.0'

    // Preferences DataStore (SharedPreferences like APIs)
    implementation "androidx.datastore:datastore-preferences:1.0.0"
    // optional - RxJava2 support
    implementation "androidx.datastore:datastore-preferences-rxjava2:1.0.0"
    // optional - RxJava3 support
    implementation "androidx.datastore:datastore-preferences-rxjava3:1.0.0"

    //Support for Java 8 features
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'

    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    implementation 'com.google.android.gms:play-services-auth:20.1.0'
}

```

</details>

### Environment information

<details>

```
# Put output below this line
Gradle 6.5
Build time:   2020-06-02 20:46:21 UTC
Revision:     a27f41e4ae5e8a41ab9b19f8dd6d86d7b384dad4
Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_321 (Oracle Corporation 25.321-b07)
OS:           Windows 11 10.0 amd64
```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/auth/emailpassword/q/platform/js/ 

### Describe the bug

I have been following the guidance from this link https://docs.amplify.aws/lib/auth/emailpassword/q/platform/js/ and when I get to Amplify.Auth.signIn(); it continues to throw the error CognitoUserSession is not valid because idToken is null. 

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line
2022-07-27 11:51:56.229 20902-20902/? I/ouse.whiteglov: Not late-enabling -Xcheck:jni (already on)
2022-07-27 11:51:56.248 20902-20902/? I/ouse.whiteglov: Unquickening 12 vdex files!
2022-07-27 11:51:56.249 20902-20902/? W/ouse.whiteglov: Unexpected CPU variant for X86 using defaults: x86
2022-07-27 11:51:56.369 20902-20902/com.beefhouse.whiteglove I/ouse.whiteglov: The ClassLoaderContext is a special shared library.
2022-07-27 11:51:56.954 20902-20902/com.beefhouse.whiteglove D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2022-07-27 11:51:56.955 20902-20902/com.beefhouse.whiteglove D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2022-07-27 11:51:56.990 20902-20976/com.beefhouse.whiteglove D/libEGL: loaded /vendor/lib/egl/libEGL_emulation.so
2022-07-27 11:51:57.002 20902-20976/com.beefhouse.whiteglove D/libEGL: loaded /vendor/lib/egl/libGLESv1_CM_emulation.so
2022-07-27 11:51:57.008 20902-20976/com.beefhouse.whiteglove D/libEGL: loaded /vendor/lib/egl/libGLESv2_emulation.so
2022-07-27 11:51:57.095 20902-20902/com.beefhouse.whiteglove W/ouse.whiteglov: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
2022-07-27 11:51:57.096 20902-20902/com.beefhouse.whiteglove W/ouse.whiteglov: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
2022-07-27 11:51:57.308 20902-20984/com.beefhouse.whiteglove D/AWSMobileClient: Using the SignInProviderConfig from `awsconfiguration.json`.
2022-07-27 11:51:57.401 20902-20984/com.beefhouse.whiteglove D/AWSMobileClient: initialize: Cognito HostedUI client detected
2022-07-27 11:51:57.419 20902-20984/com.beefhouse.whiteglove D/AWSMobileClient: Inspecting user state details
2022-07-27 11:51:57.564 20902-20902/com.beefhouse.whiteglove I/WhiteGlove: Initialized Amplify
2022-07-27 11:51:57.564 20902-20902/com.beefhouse.whiteglove D/WTF: onCreate: Fetching Auth Session
2022-07-27 11:51:57.574 20902-21000/com.beefhouse.whiteglove D/AWSMobileClient: Inspecting user state details
2022-07-27 11:51:57.576 20902-21000/com.beefhouse.whiteglove I/TetheringManager: registerTetheringEventCallback:com.beefhouse.whiteglove
2022-07-27 11:51:57.592 20902-21002/com.beefhouse.whiteglove D/AWSMobileClient: Inspecting user state details
2022-07-27 11:51:57.593 20902-21002/com.beefhouse.whiteglove D/AWSMobileClient: waitForSignIn: userState:SIGNED_OUT
2022-07-27 11:51:57.614 20902-20972/com.beefhouse.whiteglove D/HostConnection: HostConnection::get() New Host Connection established 0xead6cfc0, tid 20972
2022-07-27 11:51:57.625 20902-20972/com.beefhouse.whiteglove D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_2 
2022-07-27 11:51:57.627 20902-20972/com.beefhouse.whiteglove W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
2022-07-27 11:51:57.646 20902-20972/com.beefhouse.whiteglove D/EGL_emulation: eglCreateContext: 0xead6da40: maj 2 min 0 rcv 2
2022-07-27 11:51:57.659 20902-20972/com.beefhouse.whiteglove D/EGL_emulation: eglMakeCurrent: 0xead6da40: ver 2 0 (tinfo 0xeb0b9710) (first time)
2022-07-27 11:51:57.704 20902-20972/com.beefhouse.whiteglove I/Gralloc4: mapper 4.x is not supported
2022-07-27 11:51:57.705 20902-20972/com.beefhouse.whiteglove D/HostConnection: createUnique: call
2022-07-27 11:51:57.705 20902-20972/com.beefhouse.whiteglove D/HostConnection: HostConnection::get() New Host Connection established 0xead6d880, tid 20972
2022-07-27 11:51:57.705 20902-20972/com.beefhouse.whiteglove D/goldfish-address-space: allocate: Ask for block of size 0x100
2022-07-27 11:51:57.706 20902-20972/com.beefhouse.whiteglove D/goldfish-address-space: allocate: ioctl allocate returned offset 0x3fcd5b000 size 0x2000
2022-07-27 11:51:57.709 20902-20972/com.beefhouse.whiteglove D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_2 
2022-07-27 11:51:58.156 20902-20902/com.beefhouse.whiteglove E/libc: Access denied finding property "ro.serialno"
2022-07-27 11:51:58.148 20902-20902/com.beefhouse.whiteglove W/ouse.whiteglove: type=1400 audit(0.0:668): avc: granted { execute } for path="/data/data/com.beefhouse.whiteglove/code_cache/libjvmtiagent_x86.so" dev="dm-5" ino=132605 scontext=u:r:untrusted_app:s0:c154,c256,c512,c768 tcontext=u:object_r:app_data_file:s0 tclass=file app=com.beefhouse.whiteglove
2022-07-27 11:51:58.163 20902-21002/com.beefhouse.whiteglove W/AWSMobileClient: getCredentials: Failed to getCredentials from Cognito Identity
    com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Unauthenticated access is not supported for this identity pool. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 87c43855-bbbe-4478-93b4-4dcef89e837b)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
        at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:1836)
        at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:809)
        at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
        at com.amazonaws.mobile.client.AWSMobileClientCognitoIdentityProvider.refresh(AWSMobileClient.java:4078)
        at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:687)
        at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:474)
        at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:496)
        at com.amazonaws.mobile.client.AWSMobileClient.getCredentials(AWSMobileClient.java:400)
        at com.amazonaws.mobile.client.AWSMobileClient$1.run(AWSMobileClient.java:445)
        at com.amazonaws.mobile.client.AWSMobileClient$1.run(AWSMobileClient.java:442)
        at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:44)
        at java.lang.Thread.run(Thread.java:923)
2022-07-27 11:51:58.152 20902-20902/com.beefhouse.whiteglove W/ouse.whiteglove: type=1400 audit(0.0:669): avc: denied { read } for name="u:object_r:serialno_prop:s0" dev="tmpfs" ino=9546 scontext=u:r:untrusted_app:s0:c154,c256,c512,c768 tcontext=u:object_r:serialno_prop:s0 tclass=file permissive=0 app=com.beefhouse.whiteglove
2022-07-27 11:51:58.166 20902-21002/com.beefhouse.whiteglove D/WTF: onSucess: It worked
2022-07-27 11:51:58.170 20902-20902/com.beefhouse.whiteglove W/ouse.whiteglov: DexFile /data/data/com.beefhouse.whiteglove/code_cache/perfa.jar is in boot class path but is not in a known location
2022-07-27 11:51:58.672 20902-21031/com.beefhouse.whiteglove V/StudioTransport: Agent command stream started.
2022-07-27 11:51:58.673 20902-21030/com.beefhouse.whiteglove V/StudioTransport: Transport agent connected to daemon.
2022-07-27 11:51:58.860 20902-21035/com.beefhouse.whiteglove V/StudioTransport: Handling agent command 1200 for pid: 20902.
2022-07-27 11:51:58.860 20902-21035/com.beefhouse.whiteglove V/StudioTransport: JNIEnv not attached
2022-07-27 11:51:58.868 20902-20902/com.beefhouse.whiteglove W/Thread-6: type=1400 audit(0.0:670): avc: denied { write } for name="perfd" dev="dm-5" ino=65544 scontext=u:r:untrusted_app:s0:c154,c256,c512,c768 tcontext=u:object_r:shell_data_file:s0 tclass=dir permissive=0 app=com.beefhouse.whiteglove



```

</details>

### amplifyconfiguration.json

{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "whiteglove2": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://xxxxxxxxxxxxxxxxxx.appsync-api.us-west-2.amazonaws.com/graphql",
                    "region": "us-west-2",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS",
                    "apiKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-west-2:xxxxxxxxxxxxxxxxxxxxxxx",
                            "Region": "us-west-2"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-west-xxxxxxxxxxxxxx",
                        "AppClientId": "xxxxxxxxxxxxxxxxxxxxxxxxxxx",
                        "Region": "us-west-2"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "whiteglove2xxxxxxxxxxxxxxxxxxxx-dev.auth.us-west-2.amazoncognito.com",
                            "AppClientId": "xxxxxxxxxxxxxxxxxxxxxxxxx",
                            "SignInRedirectURI": "http://localhost:3000/",
                            "SignOutRedirectURI": "http://localhost:3000/",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [
                            "FACEBOOK",
                            "GOOGLE"
                        ],
                        "usernameAttributes": [
                            "EMAIL"
                        ],
                        "signupAttributes": [
                            "EMAIL"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                },
                "AppSync": {
                    "Default": {
                        "ApiUrl": "https://xxxxxxxxxxxxxxxxxxxxxxxxxx.appsync-api.us-west-2.amazonaws.com/graphql",
                        "Region": "us-west-2",
                        "AuthMode": "AMAZON_COGNITO_USER_POOLS",
                        "ClientDatabasePrefix": "whiteglove2_AMAZON_COGNITO_USER_POOLS"
                    },
                    "whiteglove2_API_KEY": {
                        "ApiUrl": "https://xxxxxxxxxxxxxxxxxxxxxxx.appsync-api.us-west-2.amazonaws.com/graphql",
                        "Region": "us-west-2",
                        "AuthMode": "API_KEY",
                        "ApiKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                        "ClientDatabasePrefix": "whiteglove2_API_KEY"
                    }
                }
            }
        }
    }
}

### GraphQL Schema

<details>

```graphql
// Put your schema below this line
# This "input" configures a global authorization rule to enable public access to
# all models in this schema. Learn more about authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
input AMPLIFY { globalAuthRule: AuthRule = { allow: public } } # FOR TESTING ONLY!

#type Todo @model {
#  id: ID!
#  firstName: String!
#  lastName: String!
#  description: String
#}
type User
    @model{
    #@auth(rules: [{allow: owner, operations: [create, delete, update] } ] ) {

    id: ID!
    firstName: String
    lastName: String
    teamID: ID
    team: Team @hasOne(fields: "teamID")
}

type Team
    @model {
    id: ID!
    firstName: String
    lastName: String
    date: AWSDateTime
}

```

</details>

### Additional information and screenshots

07/27 11:51:56: Launching 'app' on Pixel XL API 30.
Install successfully finished in 562 ms.
$ adb shell am start -n "com.beefhouse.whiteglove/com.beefhouse.whiteglove.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 20902 on device 'Pixel_XL_API_30 [emulator-5554]'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/ouse.whiteglov: The ClassLoaderContext is a special shared library.
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/libEGL: loaded /vendor/lib/egl/libEGL_emulation.so
D/libEGL: loaded /vendor/lib/egl/libGLESv1_CM_emulation.so
D/libEGL: loaded /vendor/lib/egl/libGLESv2_emulation.so
W/ouse.whiteglov: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/ouse.whiteglov: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
D/AWSMobileClient: Using the SignInProviderConfig from `awsconfiguration.json`.
D/AWSMobileClient: initialize: Cognito HostedUI client detected
D/AWSMobileClient: Inspecting user state details
I/WhiteGlove: Initialized Amplify
D/WTF: onCreate: Fetching Auth Session
D/AWSMobileClient: Inspecting user state details
I/TetheringManager: registerTetheringEventCallback:com.beefhouse.whiteglove
D/AWSMobileClient: Inspecting user state details
D/AWSMobileClient: waitForSignIn: userState:SIGNED_OUT
D/HostConnection: HostConnection::get() New Host Connection established 0xead6cfc0, tid 20972
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_2 
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/EGL_emulation: eglCreateContext: 0xead6da40: maj 2 min 0 rcv 2
D/EGL_emulation: eglMakeCurrent: 0xead6da40: ver 2 0 (tinfo 0xeb0b9710) (first time)
I/Gralloc4: mapper 4.x is not supported
D/HostConnection: createUnique: call
    HostConnection::get() New Host Connection established 0xead6d880, tid 20972
D/goldfish-address-space: allocate: Ask for block of size 0x100
D/goldfish-address-space: allocate: ioctl allocate returned offset 0x3fcd5b000 size 0x2000
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_2 
E/libc: Access denied finding property "ro.serialno"
W/ouse.whiteglove: type=1400 audit(0.0:668): avc: granted { execute } for path="/data/data/com.beefhouse.whiteglove/code_cache/libjvmtiagent_x86.so" dev="dm-5" ino=132605 scontext=u:r:untrusted_app:s0:c154,c256,c512,c768 tcontext=u:object_r:app_data_file:s0 tclass=file app=com.beefhouse.whiteglove
W/AWSMobileClient: getCredentials: Failed to getCredentials from Cognito Identity
    com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Unauthenticated access is not supported for this identity pool. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 87c43855-bbbe-4478-93b4-4dcef89e837b)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
        at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:1836)
        at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:809)
        at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
        at com.amazonaws.mobile.client.AWSMobileClientCognitoIdentityProvider.refresh(AWSMobileClient.java:4078)
        at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:687)
        at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:474)
        at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:496)
        at com.amazonaws.mobile.client.AWSMobileClient.getCredentials(AWSMobileClient.java:400)
        at com.amazonaws.mobile.client.AWSMobileClient$1.run(AWSMobileClient.java:445)
        at com.amazonaws.mobile.client.AWSMobileClient$1.run(AWSMobileClient.java:442)
        at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:44)
        at java.lang.Thread.run(Thread.java:923)
W/ouse.whiteglove: type=1400 audit(0.0:669): avc: denied { read } for name="u:object_r:serialno_prop:s0" dev="tmpfs" ino=9546 scontext=u:r:untrusted_app:s0:c154,c256,c512,c768 tcontext=u:object_r:serialno_prop:s0 tclass=file permissive=0 app=com.beefhouse.whiteglove
D/WTF: onSucess: It worked
W/ouse.whiteglov: DexFile /data/data/com.beefhouse.whiteglove/code_cache/perfa.jar is in boot class path but is not in a known location
V/StudioTransport: Agent command stream started.
V/StudioTransport: Transport agent connected to daemon.
V/StudioTransport: Handling agent command 1200 for pid: 20902.
    JNIEnv not attached
W/Thread-6: type=1400 audit(0.0:670): avc: denied { write } for name="perfd" dev="dm-5" ino=65544 scontext=u:r:untrusted_app:s0:c154,c256,c512,c768 tcontext=u:object_r:shell_data_file:s0 tclass=dir permissive=0 app=com.beefhouse.whiteglove
V/StudioTransport: Handling agent command 1200 for pid: 20902.
V/StudioTransport: Handling agent command 1200 for pid: 20902.
W/ouse.whiteglov: Current dex file has more than one class in it. Calling RetransformClasses on this class might fail if no transformations are applied to it!
    Accessing hidden field Landroid/database/sqlite/SQLiteClosable;->mReferenceCount:I (greylist, linking, allowed)
W/ouse.whiteglov: Current dex file has more than one class in it. Calling RetransformClasses on this class might fail if no transformations are applied to it!
    Accessing hidden method Landroid/database/sqlite/SQLiteDatabase;-><clinit>()V (blacklist, linking, denied)
    Accessing hidden field Landroid/database/sqlite/SQLiteDatabase;->DEBUG_CLOSE_IDLE_CONNECTIONS:Z (greylist-max-o, linking, denied)
    Accessing hidden field Landroid/database/sqlite/SQLiteDatabase;->sActiveDatabases:Ljava/util/WeakHashMap; (greylist-max-o, linking, denied)
    Accessing hidden field Landroid/database/sqlite/SQLiteDatabase;->CONFLICT_VALUES:[Ljava/lang/String; (greylist, linking, allowed)
    Accessing hidden method Landroid/database/sqlite/SQLiteDatabase;-><init>(Ljava/lang/String;ILandroid/database/sqlite/SQLiteDatabase$CursorFactory;Landroid/database/DatabaseErrorHandler;IIJLjava/lang/String;Ljava/lang/String;)V (greylist-max-o, linking, denied)
W/ouse.whiteglov: Accessing hidden method Landroid/database/sqlite/-$$Lambda$RBWjWVyGrOTsQrLCYzJ_G8Uk25Q;-><init>(Landroid/database/sqlite/SQLiteDatabase;)V (blacklist, linking, denied)
    Accessing hidden method Landroid/database/sqlite/SQLiteDatabase;->beginTransaction(Landroid/database/sqlite/SQLiteTransactionListener;Z)V (greylist, linking, allowed)
    Accessing hidden method Landroid/database/sqlite/SQLiteDatabase;->getThreadSession()Landroid/database/sqlite/SQLiteSession; (greylist, linking, allowed)
    Accessing hidden method Landroid/database/sqlite/SQLiteDatabase;->getThreadDefaultConnectionFlags(Z)I (greylist-max-o, linking, denied)
    Accessing hidden method Landroid/database/sqlite/SQLiteDatabase;->collectDbStats(Ljava/util/ArrayList;)V (greylist, linking, allowed)
    Accessing hidden field Landroid/database/sqlite/SQLiteDatabase;->mLock:Ljava/lang/Object; (greylist-max-o, linking, denied)
    Accessing hidden field Landroid/database/sqlite/SQLiteDatabase;-

**Comment by banji180** [comment] 2022-08-02 17:36
Can you try to clear cache and sign in again to see if that fixes it.

**Comment by gpanshu** [comment] 2022-08-05 15:22
Hi @alfdan2000 thank you for posting your question here. 

The link you pointed to is a Javascript library link and you have posted your question in the Amplify Android repo. 

Secondly looking at your logs I do not see the problem you are referring to but I do see that you are trying to login as Guest when your configuration does not allow it. 
`W/AWSMobileClient: getCredentials: Failed to getCredentials from Cognito Identity
com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Unauthenticated access is not supported for this identity pool. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 87c43855-bbbe-4478-93b4-4dcef89e837b)`
I also whipped up a sample app just in case following the tutorial [here](https://docs.amplify.aws/lib/auth/getting-started/q/platform/android/) and I was able to sign in successfully. 

If you would like to sign in with a user pool [this](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-integrating-user-pools-with-identity-pools.html) documentation may be helpful.

I am closing this issue as works as intended. If you are still facing an issue feel free to re-open with more information. I would recommend you follow the getting started guide for authentication including CLI changes that are listed and try it once more.

**Closed by gpanshu** 2022-08-05 15:22 UTC
Labels: bug, cognito, investigating
