### ISSUE TITLE
Signout does not complete when closing the browser without action

### ISSUE THREAD

**Issue by niihofutoshi** [aws-amplify/amplify-android#2598] opened 2023-09-28 08:02 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin - Coroutines

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```libs.versions.toml
// libs.versions.toml
// Put output below this line

[versions]
amplify = "2.13.2"

[libraries]
amplify-core = { module = "com.amplifyframework:core-kotlin", version.ref = "amplify" }
amplify-cognito = { module = "com.amplifyframework:aws-auth-cognito", version.ref = "amplify" }
amplify-pinpoint = { module = "com.amplifyframework:aws-push-notifications-pinpoint", version.ref = "amplify" }

```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 8.3
------------------------------------------------------------

Build time:   2023-08-17 07:06:47 UTC
Revision:     8afbf24b469158b714b36e84c6f4d4976c86fcd5

Kotlin:       1.9.0
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          20.0.1 (Homebrew 20.0.1)
OS:           Mac OS X 13.4 aarch64
```

</details>

### Please include any relevant guides or documentation you're referencing

Signout does not complete when closing the browser without action

### Describe the bug

When calling signout, if the browser is displayed and then closed without any action, the signout process does not complete.

**To Reproduce**
1. Authenticate using UserPool.
2. Use signInWithSocialWebUI for login.
3. Call the signout method.
4. When the browser is displayed, close it without any action.（If the browser doesn't display, it might be helpful to try it offline.）
5. Observe that the signout process does not complete.

**Expected behavior**
The signout process should either complete or throw an error when the browser is closed without any action.

**Possible Cause**
When the browser is closed without any action, a CancelSignOut event is issued. 
Currently, only the sign-in state is restored at this event. （[authentication](https://github.com/aws-amplify/amplify-android/blob/3e5e8695ffaaaba280fbffa19587b593442d97d7/aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/states/AuthenticationState.kt#L114), [autorization](https://github.com/aws-amplify/amplify-android/blob/3e5e8695ffaaaba280fbffa19587b593442d97d7/aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/states/AuthorizationState.kt#L146)）
It might be necessary in the [_signout](https://github.com/aws-amplify/amplify-android/blob/3e5e8695ffaaaba280fbffa19587b593442d97d7/aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt#L1843C5-L1843C5) event synchronization process to wait for the SignoutCancel event and call an error in onComplete when the SignoutCancel event is received.

### Code Snippet

```kotlin
// Put your code below this line.

println("a") // output "a"
val signOutResult = Amplify.Auth.signOut(options)
println("a") // <- does not call
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by mattcreaser** [comment] 2023-09-29 17:19
Thanks for the report @niihofutoshi. We'll take a look at this.

**Comment by mattcreaser** [comment] 2023-09-29 18:13
@niihofutoshi It looks like you are right here and there is a missing case to fix, however we would also not expect this to be a common occurrence as the browser should very quickly redirect back and close itself after signing out. We can look into fixing this but I also want to check whether you are seeing the browser staying open during a sign out?

**Comment by niihofutoshi** [comment] 2023-10-02 06:49
@mattcreaser  Thank you for your reply!
You're right, in most cases, the moment open browser, browser will be redirected to the app and the process will be completed.
However, in special cases such as when offline, the redirection may not occur, and in that case, the signout process will not be completed.

**Comment by mattcreaser** [comment] 2023-10-02 15:42
Thanks for the confirmation. We'll try to get a fix made for this issue soon.

**Comment by tylerjroach** [comment] 2023-10-20 15:18
I'm going to relabel this as a feature request, but after looking at this a bit more, this is working as intended.

v2 requires the redirect to complete before continuing with the sign out. If the user does not have a network connection, we can't actually sign the user out of the Cognito browser session.

When the user clicks the back button, there would be no way to distinguish between a user attempting to quickly cancel a sign out request, or an indication that the sign out should proceed.

This would likely require a sign out option to override user cancellation and instead continue with sign out.

**Comment by fauzimubarokk** [comment] 2024-02-21 06:33
Hello, I also get this issue, I use amplify version `2.14.7`.
Is there a newer version that has resolved this issue?

**Comment by lokeshbhattarai** [comment] 2024-05-31 12:29
@tylerjroach Is this feature request in your roadmap? Is there an ETA ?

I have a use case in my app where the user needs to be able to sign out from the app even if they are offline.

**Comment by tylerjroach** [comment] 2024-05-31 15:58
In attempting to figure out a workaround to allow sign out in no network conditions(such as manually clearing shared preferences file), I discovered the original report does contain a valid bug. This is not just a feature request.

I have observed that the onComplete callback does not fire at all (as reported), leaving auth in an invalid state where no other actions are completed. 

We will begin working on a fix to return a failed sign out in the onComplete callback, ensuring future auth calls proceed successfully.

@niihofutoshi I'm sorry for the wrong original diagnosis. Thank you for the report.

**Comment by ScottLu77** [comment] 2024-06-04 08:47
Hi, I also got this issue, I use the latest amplify 2.18.0.
Besides we encountered another similar issue.
1. we use signInWithSocialWebUI() with custom AWS SAML provider and login successfully.
2. we go to AWS cognito provider console and check "Sign-out flow"
3. Then when we sign out it, a web popup and will not redirect to our app.

Hope you could also clarify this issue. Thanks a lot.

**Comment by ScottLu77** [comment] 2024-06-05 03:03
Hi tyler, in my case, I must manually close the popup WebView, and it will receive sign out fail callback as follows

**signOutResult: FailedSignOut(exception=UserCancelledException{message=The user cancelled the sign-out attempt, so it did not complete., cause=null, recoverySuggestion=To recover: catch this error, and attempt the sign out again.})**

**Comment by tylerjroach** [comment] 2024-06-05 13:34
@ScottLu77 That is working as expected. The issue in your case is that Cognito/SAML provider is not providing the redirect back into the application. This appears to be a configuration issue on the service side. Please look into that area a bit more and create a new ticket if necessary. 

The purpose of this ticket was to make sure the `UserCancelledException` was provided when the hosted ui browser was manually closed.

@lokeshbhattarai I created a feature request ticket to track your use case: https://github.com/aws-amplify/amplify-android/issues/2842. I've given some background information in the ticket as to why the functionality is not currently present. If you have any more use case information to add, please let us know in the ticket.

**Comment by tylerjroach** [comment] 2024-12-18 15:40
Closing this ticket as we have a FR ticket

**Closed by tylerjroach** 2024-12-18 15:40 UTC
Labels: bug, auth
