### ISSUE TITLE
Cannot initialize AWSDataStorePlugin

### ISSUE THREAD

**Issue by jonivesto** [aws-amplify/amplify-android#357] opened 2020-04-07 10:17 UTC
Hello,

I'm creating an Android app that uses DataStore and GraphQL API with Cognito user pools authentication.

Running the following code crashes my application;
```
val modelProvider: ModelProvider = AmplifyModelProvider.getInstance()
Amplify.addPlugin(AWSDataStorePlugin.forModels(modelProvider))
Amplify.addPlugin(AWSApiPlugin()) // If using remote model synchronization
Amplify.configure(applicationContext)
```

However. If I remove the DataStore part, the API and authentication works with no problems.

Here is my trace:
```
W/amplify:aws-datastore: Error enqueuing mutation from subscription.
    com.amplifyframework.datastore.DataStoreException: Error during subscription.
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$3(AppSyncClient.java:1)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$8gXTT9bgLZGP51blif6hkh7EwIc.accept(Unknown Source:4)
        at com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(SubscriptionEndpoint.java:33)
        at com.amplifyframework.api.aws.SubscriptionOperation.lambda$start$0$SubscriptionOperation(SubscriptionOperation.java:4)
        at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$FXgdmzMG9ubNhC1f2NTwXyG53uo.run(Unknown Source:2)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.amplifyframework.api.ApiException: {"payload":{"errors":[{"errorType":"UnauthorizedException","message":"Missing authorization header"}]},"type":"connection_error"}
        at com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(SubscriptionEndpoint.java:33) 
        at com.amplifyframework.api.aws.SubscriptionOperation.lambda$start$0$SubscriptionOperation(SubscriptionOperation.java:4) 
        at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$FXgdmzMG9ubNhC1f2NTwXyG53uo.run(Unknown Source:2) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
W/amplify_exampl: Long monitor contention with owner pool-5-thread-1 (20680) at java.lang.String java.lang.String.substring(int, int)(String.java:2028) waiters=0 in java.lang.String com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 985ms
D/EGL_emulation: eglMakeCurrent: 0xe8151040: ver 3 0 (tinfo 0xee2f7be0)
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 1 0
W/System.err: io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | com.amplifyframework.datastore.DataStoreException: Error during subscription.
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:73)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$3JRr2oIVsg2CVfQ5dpNXlh4mgog.accept(Unknown Source:4)
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$3(AppSyncClient.java:1)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$8gXTT9bgLZGP51blif6hkh7EwIc.accept(Unknown Source:4)
        at com.amplifyframework.api.aws.SubscriptionEndpoint.notifyError(SubscriptionEndpoint.java:3)
W/System.err:     at com.amplifyframework.api.aws.SubscriptionEndpoint$1.onFailure(SubscriptionEndpoint.java:2)
        at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.kt:521)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:173)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
    Caused by: com.amplifyframework.datastore.DataStoreException: Error during subscription.
    	... 10 more
W/System.err: Caused by: com.amplifyframework.api.ApiException: Subscription failed.
        at com.amplifyframework.api.aws.SubscriptionEndpoint.notifyError(SubscriptionEndpoint.java:2)
    	... 7 more
    Caused by: java.io.EOFException
        at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
W/System.err:     at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
        at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:113)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:96)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:241)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:171)
    	... 4 more
E/AndroidRuntime: FATAL EXCEPTION: OkHttp https://irk3p4l7dzdtnit5kayrslpl34.appsync-realtime-api.eu-west-2.amazonaws.com/...
    Process: fi.finlabs.toyl_amplify_example, PID: 20436
    io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | com.amplifyframework.datastore.DataStoreException: Error during subscription.
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:73)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$3JRr2oIVsg2CVfQ5dpNXlh4mgog.accept(Unknown Source:4)
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$3(AppSyncClient.java:1)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$8gXTT9bgLZGP51blif6hkh7EwIc.accept(Unknown Source:4)
        at com.amplifyframework.api.aws.SubscriptionEndpoint.notifyError(SubscriptionEndpoint.java:3)
        at com.amplifyframework.api.aws.SubscriptionEndpoint$1.onFailure(SubscriptionEndpoint.java:2)
        at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.kt:521)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:173)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.amplifyframework.datastore.DataStoreException: Error during subscription.
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$3(AppSyncClient.java:1) 
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$8gXTT9bgLZGP51blif6hkh7EwIc.accept(Unknown Source:4) 
        at com.amplifyframework.api.aws.SubscriptionEndpoint.notifyError(SubscriptionEndpoint.java:3) 
        at com.amplifyframework.api.aws.SubscriptionEndpoint$1.onFailure(SubscriptionEndpoint.java:2) 
        at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.kt:521) 
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:173) 
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: com.amplifyframework.api.ApiException: Subscription failed.
        at com.amplifyframework.api.aws.SubscriptionEndpoint.notifyError(SubscriptionEndpoint.java:2)
        at com.amplifyframework.api.aws.SubscriptionEndpoint$1.onFailure(SubscriptionEndpoint.java:2) 
        at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.kt:521) 
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:173) 
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.io.EOFException
        at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
        at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
        at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:113)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:96)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:241)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:171)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
I/Process: Sending signal. PID: 20436 SIG: 9
```

**Comment by jamesonwilliams** [comment] 2020-04-07 12:02
Hi @jonivesto, thanks for reporting this!

This looks to be like a dupe of https://github.com/aws-amplify/amplify-android/issues/185. Basically, subscriptions only work with API key auth, at the moment. We still need to add in the author auth mechanisms.

For the immediate short term, you could disable cloud synchronization, or switch to API key auth.

**Closed** 2020-04-07 12:06 UTC
Labels: DataStore, Duplicate, Usage Question

**Comment by jonivesto** [comment] 2020-04-07 14:56
@jamesonwilliams Thanks for the quick response.

Do you have any estimate on when will this be supported? #185 was reported months ago..

Also, you should probably mention the issue in the docs, so other people don't find themselves reading this.

**Comment by jpignata** [comment] 2020-04-08 13:38
That's a good point @jonivesto -- thank you! We'll add a caveat. This is high on our list and we intend to get it out in the next couple of preview releases.
